### ISSUE TITLE
Function "eventsFromRange"

### ISSUE THREAD

**Issue by ArthurProvost** [u01jmg3/ics-parser#104]
It is possible to call this function with a date (with hours and minutes) like this: `2016-01-20 02:00` (instead of `2016-03-01`, as you mentioned in you example code) by modifying your code ?

**Comment by u01jmg3** [comment]
Yes that will work. The [function](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1388) creates a `DateTime` object.

Will update the example - thanks for spotting
