### ISSUE TITLE
"Unfolding" not implemented

### ISSUE THREAD

**Issue by ComiR** [u01jmg3/ics-parser#111]
Hi,

I just stared to use your package and ran into an issue where all properties got mixed up. I could track it down to being caused by the line folding (https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html).

I solved it with `$iCal->initString(str_replace(["\r\n ", "\r\n\t"], '', $content))`.

BTW: the `explode()` you use should probably use `\r\n` (see link above).

**Comment by u01jmg3** [comment]
Does 70137bb suffice?

**Comment by ComiR** [comment]
I didn't test, but I don't think this is what you want here.

The standard defines the use of `\r\n` (aka CRLF) as a divider.
It also explicitly states to "unfold" (i.e. strip every CRLF followed by a "linear white-space character" [i.e. ` ` or `\t`]) *before* doing anything else.

btw: `removeInvalidChars()` only accepts ASCII values instead of Unicode...

**Comment by u01jmg3** [comment]
8bf91cc, c9786f5 should do a better job 👍

**Comment by u01jmg3** [comment]
Closing as I believe I have covered the issues that have been raised - if I haven't, happy to re-open.
