### ISSUE TITLE
Support ability to skip `processRecurrences()`

### ISSUE THREAD

**Issue by AgamlaRage** [u01jmg3/ics-parser#112]
Hi,

Is there currently a way to disable the `processRecurrences()` function, or to only get the non-recurring events + the "parent" events?

In my particular case, I already have a `processRecurrences` system in my app, that parses rrule and I would like to only get the events that are not recurring.

I didn't find a way to achieve this without extending/modifying the class.

Thanks

**Comment by u01jmg3** [comment]
Not currently but I can build it

**Comment by AgamlaRage** [comment]
Thx for your reactivity :)
