### ISSUE TITLE
Error when EXDATE spans multiple lines

### ISSUE THREAD

**Issue by acmurmeltier69** [u01jmg3/ics-parser#114]
(I think this is not related to #113, so I created a separate issue)

If a set of excluded dates is added via EXDATE, the system returns the wrong dates after the initial week.

>DTSTART;VALUE=DATE:20170313
>RRULE:FREQ=WEEKLY;UNTIL=20171224T000000Z;INTERVAL=2;BYDAY=MO;WKST=SU
>EXDATE;VALUE=DATE:
>20170410,
>20170605

It appears that the concatenation in [ICal.php Line 379](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L379)  adds the dates to the wrong line (i.e. the RRULE line above)

In contrast, if EXDATE is presented in a single row, the dates seem to be correct 

>DTSTART;VALUE=DATE:20170313
>RRULE:FREQ=WEEKLY;UNTIL=20171224T000000Z;INTERVAL=2;BYDAY=MO;WKST=SU
>EXDATE;VALUE=DATE:20170410,20170605

**Comment by u01jmg3** [comment]
- Problem surrounds [this line](https://github.com/u01jmg3/ics-parser/blob/1cafc4c930bcb0daf1ee96cbe3c47999b36e438d/src/ICal/ICal.php#L256-L258) where the parser blanks what it believes to be a key missing a value
- Debating what to do as each line of an iCal file _should_ be a key/value pair
  - `EXDATE` _should_ follow the same pattern just as its [spec definition](http://www.kanzaki.com/docs/ical/exdate.html#def) states

**Comment by acmurmeltier69** [comment]
Hi

unfortunately the iCAL spec RFC5545 allow more flexibility (See [sectiont 2 content lines](https://tools.ietf.org/html/rfc5545#page-8))
".. a long    line can be split between any two characters by inserting a CRLF  immediately followed by a single linear white-space character"

**Comment by acmurmeltier69** [comment]
this seems to do the job:
adding 
>			$lines = explode("\r\n",$this->unfold(implode("\r\n", $lines)));

after line 172

**Comment by u01jmg3** [comment]
Got a fix coming
