### ISSUE TITLE
Support ability to parse multiple EXDATE lines

### ISSUE THREAD

**Issue by acmurmeltier69** [u01jmg3/ics-parser#115]
Found another strange RRULE that is allowed by the spec but doesn't parse correctly:

```
DTSTART;VALUE=DATE:20170303
DTEND;VALUE=DATE:20170304
RRULE:FREQ=WEEKLY;UNTIL=20171231;BYDAY=FR;WKST=MO
EXDATE:20170414T000000
EXDATE:20170421T000000
EXDATE:20170505T000000
EXDATE:20170526T000000
EXDATE:20170616T000000
EXDATE:20170818T000000
EXDATE:20171006T000000
EXDATE:20171103T000000
EXDATE:20171229T000000
```

This seems to be allowed by RF5545 ([section 3.1.2 multiple values](https://tools.ietf.org/html/rfc5545#section-3.1.2)).

The current code seems to use only the first occurrence.

**Comment by u01jmg3** [comment]
More tricky to solve but got a solution that will need coding

**Comment by acmurmeltier69** [comment]
Looks like the block in ICal.php following [line 378](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L378) is supposed to do just that.
But somehow doesn't work the way it should
