### ISSUE TITLE
Multi-Line Key-Value Pair causes crash

### ISSUE THREAD

**Issue by spalberg** [u01jmg3/ics-parser#117]
I've imported a event that contained the following snippet:

    DTEND;TZID=W. Europe Standard Time:20170228T150000
    UID:
     040000008200E00074C5B7101A82E0080000000010D4424FBA91D201000000000000000010
     000000A24BA6B406C12B49BDCA786126F1415C
    CLASS:PUBLIC

This causes the following exception:
```
Uncaught Exception: DateTime::__construct(): Failed to parse time string (20170228T150000040000008200E00074C5B7101A82E0080000000010D4424FBA91D201000000000000000010000000A24BA6B406C12B49BDCA786126F1415C) at position 15 (0): Double date specification in /var/www/html/vendor/johngrogg/ics-parser/src/ICal/ICal.php:593
```

As far as I can tell the parser "drops" the `UID` line because it's a key without a value. When it reaches the next lines it adds both `UID`-value-parts to the `DTEND` since this is the last not-dropped key. After that the value array for `DTEND` gets joined causing this invalid datetime string. 

Since this is the only event with this kind of problem, is this even a valid format?
If it is, can you allow keys without value in the same line to solve this problem or would this create other problems?

**Comment by u01jmg3** [comment]
Thanks for logging the issue.

Are you using the latest `dev-master`? This should all be sorted as recently I have been working on hardening the parser against multiline content.

**Comment by spalberg** [comment]
Thanks for the fast response!
You are right, I was using `v2.0`. Must have forgotten that when installing it via composer.
It is working with `dev-master`, thanks!
