### ISSUE TITLE
`cleanData()` conversion problem

### ISSUE THREAD

**Issue by Nefro9** [u01jmg3/ics-parser#118]
Hello,

`cleanData()` function not working with word `pažiūrėti`, it returns `pažiūr�--ti`

```
$cleanedData = str_replace(array(chr(145), chr(146), chr(147), chr(148), chr(150), chr(151), chr(133), chr(194)), $replacementChars, $cleanedData);
```

**Comment by u01jmg3** [comment]
Thanks for logging the issue.

Are you using the latest `dev-master`? A recent change provides support for cleaning both ascii and unicode characters.

**Comment by Nefro9** [comment]
Yes, I'm using latest dev-master

**Comment by Nefro9** [comment]
Thank you, now it's work 👍
