### ISSUE TITLE
Getting fatal error with time construct

### ISSUE THREAD

**Issue by mansj** [u01jmg3/ics-parser#120]
Hi,

I'm trying to parse a downloaded .ics from iCloud (using public calendar and wget:ing the ics) but I keep getting the following errors:

`Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string`

I've tried removing a few of the (old) ical events which seem to cause the hickup, but the problems seems to be with a lot of events. 

Example error message:

```
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (20160523T120000/aMjg0NzQyMDMxMjg0NzQyMBepsf5Xfb3eCoSvMo2mL1qkLACjUXgKOEg0G9GgEq_I/principal/) at position 15 (/): Unexpected character' in /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php:593 Stack trace: #0 /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php(593): DateTime->__construct('20160523T120000...', Object(DateTimeZone)) #1 /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php(1350): ICal\ICal->iCalDateWithTimeZone(Array, 'DTSTART', true) #2 /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php(318): ICal\ICal->processDateConversions() #3 /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php(180): ICal\ICal->initLines(Array) #4 /home/dashboard2/inc_ical.php( in /home/dashboard2/vendor/johngrogg/ics-parser/src/ICal/ICal.php on line 593
```

**Comment by u01jmg3** [comment]
As per the guidelines:

> - It is also extremely useful to be provided with an iCal snippet causing the parser to behave incorrectly

**Comment by mansj** [comment]
Ah, sorry. I can only use the datetime in the error message to determine what event is causing errors, right now (as in the example above) I am assuming its this:

`BEGIN:VEVENT
CREATED:20160517T072631Z
UID:7C243F27-9315-4FB3-B6BE-6C6AA04700C5
DTEND;TZID=Europe/Stockholm:20160523T130000
ATTENDEE;CUTYPE=INDIVIDUAL;EMAIL=elisabeth.nilsson@tinitus.com;
 PARTSTAT=ACCEPTED;ROLE=CHAIR;CN=Elisabeth Nilsson:
 /aMjg0NzQyMDMxMjg0NzQyMBepsf5Xfb3eCoSvMo2mL1qkLACjUXgKOEg0G9GgEq_I/princip
 al/
ATTENDEE;CUTYPE=INDIVIDUAL;EMAIL=mans.jonasson@iis.se;PARTSTAT=ACCEPTED;
 X-CALENDARSERVER-DTSTAMP=20160517T074001Z;CN=Måns Jonasson:
 /aMTg1NjExMjY1MTg1NjExMl0dmUZ1xLZ-Xd-lLltxJyBVJkO5S-FxpUZmF9Yy29e9/princip
 al/
ATTENDEE;CN=Niklas Seren;CUTYPE=INDIVIDUAL;EMAIL=niklas.seren@iis.se;
 PARTSTAT=ACCEPTED:mailto:niklas.seren@iis.se
ATTENDEE;CN=Therese Ernbrandt;CUTYPE=INDIVIDUAL;
 EMAIL=therese.ernbrandt@iis.se;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:
 therese.ernbrandt@iis.se
SUMMARY:Badminton!!!
DTSTART;TZID=Europe/Stockholm:20160523T120000
ORGANIZER;CN=Elisabeth Nilsson;EMAIL=elisabeth.nilsson@tinitus.com:
 /aMjg0NzQyMDMxMjg0NzQyMBepsf5Xfb3eCoSvMo2mL1qkLACjUXgKOEg0G9GgEq_I/princip
 al/
SEQUENCE:0
DTSTAMP:20160523T062413Z
END:VEVENT`

**Comment by u01jmg3** [comment]
- Using the latest `dev-master` with the event you have provided, I get no error.
- Are you sure this is the offending event?

<img width="254" alt="event" src="https://cloud.githubusercontent.com/assets/1266205/24550553/7aa41142-1616-11e7-9634-4f510d441a43.png">

**Comment by mansj** [comment]
I'm also using dev-master, just installed yesterday. 

No, it's hard to be sure - how could I verify other than searching my large .ics for the date/time of the event and the string "aMjg0NzQyMDMxMjg0NzQ....."? 

This is the only event in my entire .ics file which has that date and string.

**Comment by mansj** [comment]
I've (manually) removed the suspected event from my .ics now, and as before I get errors on another event:

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (20131009T150000SUMMARY:Meet lamp people

It looks to me like the script somehow thinks that SUMMARY and the title is part of the date. 

Could something be wrong with the file encoding, so certain newlines are not recognized?

**Comment by mansj** [comment]
I have identified that the problem lies somewhere in the function `addCalendarComponentWithKeyAndValue`, and specifically where the multi-line glue stuff happens. For some reason, some strings are glued together that should not be. 

Still bug-hunting...

**Comment by mansj** [comment]
OK, it seems that the problem is around line 336:

if ($keyword == false) {
   $keyword = $this->lastKeyword;
}

This concatenates too much into the datetime for me.

**Comment by u01jmg3** [comment]
Can you provide the ICS file?

**Comment by mansj** [comment]
@u01jmg3 Yes, but since it's my private calendar I'd rather email it direct to you. What address?

**Comment by u01jmg3** [comment]
- GitHub username [at] [gmail] [dot] [com]
- Appreciate you sharing your private calendar to get this sorted

**Comment by mansj** [comment]
Sent it now.

**Comment by u01jmg3** [comment]
- Just ran the parser against the iCal file you provided and it parses your file without issue returning `2,825` events in total.

Attempting to debug some more:

- What version of PHP are you running?
  - Must be 5.3.8+
- What code specifically are you running to use the parser and produce the error?
- Are you on a Windows/Linux/Mac machine?
  - Line endings shouldn't be an issue especially as you have provided the exact iCal file.
- Can I double check that you definitely have the latest `dev-master`?
  - Sorry to ask again but I have to make sure.
- Are you able to put a test version online so I can see the issue?
  - I appreciate this is your personal calendar but even if you could demonstrate the error you are seeing with just one event.
- I don't believe this is timezone related and I have checked using `date_default_timezone_set('Europe/Rome');` which appears to be your timezone

**Comment by mansj** [comment]
_What version of PHP are you running?_
PHP Version 5.6.30-0

_What code specifically are you running to use the parser and produce the error?_
`use ICal\ICal;

$ical = new ICal('icloud.ics', array(
    'defaultSpan'           => 2,
    'defaultWeekStart'      => 'MO',
    'skipRecurrence'        => false,
    'useTimeZoneWithRRules' => false,
));

$events = $ical->eventsFromInterval('2 day');

`
_Are you on a Windows/Linux/Mac machine?_
Debian 8.7 jessie

_Can I double check that you definitely have the latest dev-master?_
Yes, just downloaded it again from GitHub just to make sure.

.... AND of course it works now. :)

The way I installed it originally (4 days ago) was using:

´php -f composer.phar require johngrogg/ics-parser´

Is this wrong?

Another thing though: I had to set_time_limit(0) on my PHP code since parsing my calendar takes over 30 seconds. Is this normal?

**Comment by u01jmg3** [comment]
- So it's working for you?! 🎉 Great news :)
- Think your command should be: `php -f composer.phar require johngrogg/ics-parser:dev-master` to pull in `dev-master`
- In the past I have tried to improve the parser speedwise but unfortunately your iCal file is on the large side (>18,200 lines).
  - Usually iCal applications reduce iCal output to future events and past events `-1` year or such like.
  - For example, your iCal has events from 2010 (-7 years).

**Comment by mansj** [comment]
Yes, working fine now with the latest version. 

I think now that I _did_ get out that dev-master-version, but I did it _after_ I had got the first version, so it might not have overwritten the older version? Anyway. Works now. Thanks for all your help!
