### ISSUE TITLE
crash on invalid calendar date

### ISSUE THREAD

**Issue by acmurmeltier69** [u01jmg3/ics-parser#123]
Hello

(another issue, sorry!)
One of my users observed a crash with a calendar file he downloaded from his citie's webpage.

It turned out that the file contained an invalid date

```
BEGIN:VEVENT
DTSTART:2017103**2**T000000
DTEND:20171101T2300
SUMMARY:Biotonne
DESCRIPTION:Biotonne muss bereitgestellt werden.
DTSTAMP:20170406T063924
LOCATION:Vechelde a
UID:f81b0b41a2e138ae0903daee0a966e1e
SEQUENCE:0
END:VEVENT
```

Obviously this is wrong.
However, is there a way to ignore such a situation more gracefully?

At the moment I get
```
Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (20171032T000000) at position 7 (2): Unexpected character' in ICal\ICal.php:575 Stack trace: #0 ICal\ICal.php(575): DateTime->__construct('20171032T000000', Object(DateTimeZone)) #1 ICal\ICal.php(1355): ICal\ICal->iCalDateWithTimeZone(Array, 'DTSTART', true) #2 ICal\ICal.php(322): ICal\ICal->processDateConversions() #3 ICal\ICal.php(185): ICal\ICal->initLines(Array) #4 
```

or should I just put a
`try {} catch {}` around the constructor?

**Comment by u01jmg3** [comment]
Let me have a look

**Comment by acmurmeltier69** [comment]
thanks.
I managed to safely catch the exception in my app. 
So it is not blocking me. (Still worth investigating, however)
