### ISSUE TITLE
Support longer description field

### ISSUE THREAD

**Issue by dxdc** [u01jmg3/ics-parser#124]
- PHP Version: `5.5.38`

### Description of the Issue:

Within the ICS file, only the first line of multi-line `DESCRIPTION` is returned. In this example, only `Name: Bill` would be returned.

`ics snippet`
```ics
BEGIN:VEVENT
SUMMARY:The event summary
DESCRIPTION:Name: Bill\n
 Facility: Shop1\n
 Shift: Morning\n
 Shift Type: Floor
END:VEVENT
```

### Steps to Reproduce:

See above. Only the first line of the description field is returned.

**Comment by u01jmg3** [comment]
- This is only a partial event but from initial testing the parser correctly returns the complete description.

<img width="494" alt="demo" src="https://cloud.githubusercontent.com/assets/1266205/25028352/a292979c-20ab-11e7-9923-e07e04ee02d0.png">

**Comment by dxdc** [comment]
Thanks for the reply @u01jmg3. I'm curious, how are you loading this into the EventObject? I wonder if it's because I'm loading it into a file? I get identical behavior with either of the below scripts.

```php
$raw_ics_data = file_get_contents('file.ics');
$ical = new ICal( explode( "\n", $raw_ics_data ) );
$events = $ical->events();
print_r($events);
```

```php
$ical = new ICal('file.ics');
$events = $ical->events();
print_r($events);
```

try this: `file.ics`
```
BEGIN:VCALENDAR
VERSION:2.0
X-PUBLISHED-TTL:PT5M
PRODID:Testing\, LLC\, domain.com Version 1.0
METHOD:PUBLISH
BEGIN:VEVENT
UID:PRODUCTIONORG462SS208@domain.com
SEQUENCE:2
DTSTAMP:20170413T223147Z
DTSTART:20170301T123000Z
DTEND:20170301T203000Z
SUMMARY:Day S John
DESCRIPTION:Group: University of XYZ\n
 Facility: Facility 1\n
 Shift: Morning South\n
 Shift Type: Cashier
END:VEVENT
END:VCALENDAR
```

**Comment by u01jmg3** [comment]
> _I'm curious, how are you loading this into the EventObject?_

- The [`EventObject`](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/EventObject.php) is [part of the parser](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1389)

> _I wonder if it's because I'm loading it into a file?_

- The example provided with the parser [loads its events using a file](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L6) so that won't be the problem.

---

- Tested again with your complete iCal and I get the same (correct) output as before.
- Here is the [same code used in the example](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L2-L11) - I point you to this [in the README](https://github.com/u01jmg3/ics-parser/blob/master/README.md#how-to-instantiate-the-parser)

```php
<?php
require_once '../vendor/autoload.php';

use ICal\ICal;

$ical = new ICal('file.ics', array(
    'defaultSpan'           => 2,     // Default value
    'defaultWeekStart'      => 'MO',  // Default value
    'skipRecurrence'        => false, // Default value
    'useTimeZoneWithRRules' => false, // Default value
));

var_dump($ical->events());
```

**Comment by dxdc** [comment]
@u01jmg3 Thanks for continuing to look into this. I had already tested your example script, which has the same behavior, and strangely, it's still not working. Do you think it's a PHP setting for multiline processing?

Here is the PHP script, with the same `file.ics` I showed above. The `description` array is still chopped off. I just made a slight modification to hardcode the timezone in this particular case.

```
php -v
PHP 5.6.29 (cli) (built: Dec  8 2016 23:03:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

```php
<?php
require_once __DIR__.'/vendor/autoload.php';

use ICal\ICal;

if ( !ini_get( 'date.timezone' ) )
            date_default_timezone_set( 'America/Chicago' );

$ical = new ICal('file.ics', array(
    'defaultSpan'           => 2,     // Default value
    'defaultWeekStart'      => 'MO',  // Default value
    'skipRecurrence'        => false, // Default value
    'useTimeZoneWithRRules' => false, // Default value
));

var_dump($ical->events());

?>
```

You can see the full output of this script, below.

```
array(1) {
  [0]=>
  object(ICal\EventObject)#4 (24) {
    ["summary"]=>
    string(10) "Day S John"
    ["dtstart"]=>
    string(16) "20170301T123000Z"
    ["dtend"]=>
    string(16) "20170301T203000Z"
    ["duration"]=>
    NULL
    ["dtstamp"]=>
    string(16) "20170413T223147Z"
    ["uid"]=>
    string(32) "PRODUCTIONORG462SS208@domain.com"
    ["created"]=>
    NULL
    ["lastmodified"]=>
    NULL
    ["description"]=>
    string(24) "Group: University of XYZ"
    ["location"]=>
    NULL
    ["sequence"]=>
    string(1) "2"
    ["status"]=>
    NULL
    ["transp"]=>
    NULL
    ["organizer"]=>
    NULL
    ["attendee"]=>
    NULL
    ["uid_array"]=>
    array(2) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(32) "PRODUCTIONORG462SS208@domain.com"
    }
    ["sequence_array"]=>
    array(2) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(1) "2"
    }
    ["dtstamp_array"]=>
    array(2) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(16) "20170413T223147Z"
    }
    ["dtstart_array"]=>
    array(3) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(16) "20170301T123000Z"
      [2]=>
      int(1488371400)
    }
    ["dtend_array"]=>
    array(3) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(16) "20170301T203000Z"
      [2]=>
      int(1488400200)
    }
    ["summary_array"]=>
    array(2) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(10) "Day S John"
    }
    ["description_array"]=>
    array(2) {
      [0]=>
      array(0) {
      }
      [1]=>
      string(26) "Group: University of XYZ\n"
    }
    ["dtstart_tz"]=>
    string(15) "20170301T063000"
    ["dtend_tz"]=>
    string(15) "20170301T143000"
  }
}
```

**Comment by u01jmg3** [comment]
Might be best to upload your `*.ics` file in this issue as the problem could be line endings

**Comment by dxdc** [comment]
@u01jmg3 I can't upload to github for some reason, but you can download the sample project here.

https://www.dropbox.com/s/qwcu7an9zy0tmfn/demo.zip?dl=1

**Comment by u01jmg3** [comment]
- Sigh - your code works perfectly for me.
- It must therefore be something to do with your setup.
- I recently made [this commit](https://github.com/u01jmg3/ics-parser/commit/07e775faef4bb6dca7440b59060cdfd99e211757#diff-50681920b8994c51dcfbb9a44850348fR171) to support line endings on Macs.
- Without having access to your setup to reproduce the issue I have no way of solving this.

<img width="407" alt="demo" src="https://cloud.githubusercontent.com/assets/1266205/25181087/440d8086-2508-11e7-9b78-3123d3d6d25a.png">

**Comment by dxdc** [comment]
@u01jmg3 Well, at least we've isolated the issue :) which version of PHP are you using? Can you also provide your PHP.ini?

**Comment by dxdc** [comment]
Btw. the `ini_set` function had no effect for me. I can easily reproduce this issue on Linux and Mac.

**Comment by u01jmg3** [comment]
- Do you have access to a Windows machine to rule that out?
- `5.6.19`
- [`php.ini`](https://gist.github.com/u01jmg3/7fce736b23631df09ed65f1aef06eeed)

**Comment by u01jmg3** [comment]
Are you able to debug and try removing the `\n` in your iCal to see if you get the other lines through the parser?

**Comment by dxdc** [comment]
@u01jmg3 I tried removing `\n` (and even the leading space), no effect unfortunately. I also tried setting `ini_set('auto_detect_line_endings', true);`. Neither changed the parsed result.

**Comment by u01jmg3** [comment]
Try changing the [`EventObject` constructor](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/Event.php#L124-L129) to `var_dump($data)` to see what you get

**Comment by dxdc** [comment]
Just tried with vanilla PHP5 and PHP7 installs on Linux. No change.

If I add `var_dump($data)` to the EventObject constructor (I couldn't just eliminate the existing function, it produced `NULL` response), the only difference in behavior I see is the addition of `\n` at the end of the DESCRIPTION field.

E,g,
`"Group: University of XYZ\n"` (with this change) vs. `"Group: University of XYZ"` (original). I think there must be other line handling issues elsewhere in the code?

**Comment by dxdc** [comment]
I found the issue and submitted a PR for you.

**Comment by u01jmg3** [comment]
~~Try adding `var_dump($lines)` to the [`ICal` constructor](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L178) to see what PHP returns when it reads your iCal file~~

**Comment by dxdc** [comment]
I think the best way to deal with this is to directly manipulate the $lines array and skip the whole implode/explode part.

We can find array elements that have `tab` or `space` as their first character and merge with the previous array. This would allow us to use the built-in spec for `auto_detect_line_endings`.

**Comment by u01jmg3** [comment]
Feel free to pull together another PR - currently I only have time to fix bugs rather than explore enhancements. I can help where necessary
