### ISSUE TITLE
Support ability to parse METHOD

### ISSUE THREAD

**Issue by Nefro9** [u01jmg3/ics-parser#126]
Hello, is it possible to parse `METHOD`?

I want to delete a calendar event then get .ics with `METHOD:CANCEL`

**Comment by u01jmg3** [comment]
Please provide an example iCal event

**Comment by Nefro9** [comment]
After delete event, I get this ICS (thunderbird)

[demo.zip](https://github.com/u01jmg3/ics-parser/files/929623/demo.zip)

**Comment by u01jmg3** [comment]
- Once I have made a change to the parser you will be able to access it via:

    ```php
    $ical = new ICal('ICal.ics');
    var_dump($ical->cal['VCALENDAR']['METHOD']);
    ```
