### ISSUE TITLE
Recurring events do not persist the original time

### ISSUE THREAD

**Issue by jvihavainen** [u01jmg3/ics-parser#127]
- PHP Version: `5.6.30`
- PHP date.timezone: `America/Los_Angeles`
- ics-parser version: `dev-master`

### Description of the Issue:
When ICS from Google Calendar with Los Angeles timezone is loaded with the latest code from dev-master, the recurring events are not persisting the correct time.

The outlined example below for event "Pep Rally" shows how an event that first occurred on 2016/09/12 at 8:30am appears to reoccur on 2017/04/03 at 13:00pm, when it should always be at 8:30am. Only the original event on 2016/09/12 shows the correct time.

### Steps to Reproduce:
Use the attached test.ics file with the example code to see that the 8:30am initial time is not persisted to recurring events generated by the ICal class.

[test.ics.zip](https://github.com/u01jmg3/ics-parser/files/931992/test.ics.zip)

```
$ical = new ICal('test.ics', ['useTimeZoneWithRRules' => true]);
foreach ($ical->events() as $event):
echo $event->printData();
endforeach;
exit;
```

### Example of Recurring Event ICS Data:

> BEGIN:VEVENT
> DTSTART;TZID=America/Los_Angeles:20160912T083000
> DTEND;TZID=America/Los_Angeles:20160912T093000
> RRULE:FREQ=WEEKLY;UNTIL=20170619T153000Z;BYDAY=MO
> EXDATE;TZID=America/Los_Angeles:20170529T083000
> EXDATE;TZID=America/Los_Angeles:20170327T083000
> DTSTAMP:20170419T042751Z
> UID:0j29abh6ribfbegct0alrvma3k@google.com
> CREATED:20170227T154218Z
> DESCRIPTION:
> LAST-MODIFIED:20170413T125723Z
> LOCATION:
> SEQUENCE:0
> STATUS:CONFIRMED
> SUMMARY:Pep Rally
> TRANSP:OPAQUE
> END:VEVENT

### Example of Incorrect ICal Output:

> SUMMARY: Pep Rally
> DTSTART: 20170403T013000
> DTEND: 20170403T023000
> DTSTART_TZ: 20170403T013000
> DTEND_TZ: 20170403T023000
> DTSTAMP: 20170419T055733Z
> UID: 0j29abh6ribfbegct0alrvma3k@google.com
> CREATED: 20170227T154218Z
> STATUS: CONFIRMED
> TRANSP: OPAQUE

**Comment by u01jmg3** [comment]
- Thanks for logging this issue.
- Confirmed on my end - relates to time zones being applied when they are already combined with a timestamp.
- Time zones in general have been quite tricky to implement.
- To simplify things I will make a change to rely on `DTSTART_TZ` and `DTEND_TZ` for time zone manipulated timestamps (leaving `DTSTART` and `DTEND` untouched and in their original state).
