### ISSUE TITLE
Duplicate event for recurring meeting instance exception

### ISSUE THREAD

**Issue by jasonheffner** [u01jmg3/ics-parser#129]
- PHP Version: `5.6.30`
- PHP date.timezone: `America/New_York`

### Description of the Issue:
Duplicate meetings for recurring meetings. This happens on meetings that have single occurrences that have different times.

### Steps to Reproduce:

Example iCal from Zimbra. On 20/04/2017 there should be 2x 1 hour meetings at 9:00 and ~~15:30~~ **14:00**. Instead ~~4x~~ **3x** meetings are returned. ~~Two~~ **One** is a duplicate.

- https://gist.github.com/jasonheffner/eeb934d3edd29bc50ee40580e6890459

**Comment by u01jmg3** [comment]
- Looking at your iCal and focussing on `20-04-2017`, the parser returns 3 events.
- These 3 events are defined separately in your iCal so the parser is correct with its output.

<img width="793" alt="demo" src="https://cloud.githubusercontent.com/assets/1266205/25255225/7eb6bc06-2621-11e7-8fc8-68d65f65ea73.png">

---

- In total your iCal contains `7` events but here are the `3` that have events occurring on `20-04-2017`:

```
BEGIN:VEVENT
UID:e12d2536-d35b-4917-9573-5670003d9802
RRULE:FREQ=WEEKLY;UNTIL=20170601T035959Z;INTERVAL=2;BYDAY=TH
SUMMARY:CREATE Bi-weekly mtgs.
DESCRIPTION:\n
X-ALT-DESC;FMTTYPE=text/html:<html><body id='htmlmode'></body></html>
LOCATION:Shields (J Franklin)\,003C\,UP
DTSTART;TZID="America/New_York":20170420T090000
DTEND;TZID="America/New_York":20170420T100000
STATUS:CONFIRMED
CLASS:PUBLIC
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
TRANSP:OPAQUE
LAST-MODIFIED:20170315T201152Z
DTSTAMP:20170315T201152Z
SEQUENCE:0
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT15M
DESCRIPTION:Reminder
END:VALARM
END:VEVENT

BEGIN:VEVENT
UID:e9968032-846d-4c26-8839-e2c49bbbf9d3
SUMMARY:Student Forecasting/ Advising Project Meeting
LOCATION:shieldsjfranklin-003c-up
DTSTART;TZID="America/New_York":20170420T140000
DTEND;TZID="America/New_York":20170420T150000
STATUS:CONFIRMED
CLASS:PUBLIC
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
TRANSP:OPAQUE
RECURRENCE-ID;TZID="America/New_York":20170420T153000
LAST-MODIFIED:20170414T175947Z
DTSTAMP:20170414T175947Z
SEQUENCE:2
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT15M
DESCRIPTION:Reminder
END:VALARM
END:VEVENT

BEGIN:VEVENT
UID:e9968032-846d-4c26-8839-e2c49bbbf9d3
RRULE:FREQ=WEEKLY;UNTIL=20170519T035959Z;INTERVAL=1;BYDAY=TH
SUMMARY:Student Forecasting/ Advising Project Meeting
LOCATION:shieldsjfranklin-003c-up
DTSTART;TZID="America/New_York":20170406T153000
DTEND;TZID="America/New_York":20170406T163000
STATUS:CONFIRMED
CLASS:PUBLIC
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
TRANSP:OPAQUE
LAST-MODIFIED:20170208T154316Z
DTSTAMP:20170208T154316Z
SEQUENCE:1
EXDATE;TZID="America/New_York":20170427T153000
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT15M
DESCRIPTION:Reminder
END:VALARM
END:VEVENT
```

**Comment by jasonheffner** [comment]
The one event is a single occurrence of a repeating event. In your translation of the ical you'll notice the EXDATE tag. That should replace the recurring event above that.. The 2:00 meeting should not show up. In my linked gist version it's denoted as RECURRENCE-ID.

**Comment by u01jmg3** [comment]
Gotcha.

There is an issue of time zones being re-applied when populating [`alteredRecurrenceInstances()`](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L636-L642) which controls `RECURRENCE-ID` info.

However, when fixing this, it is the `15:30` event which is removed not the `14:00`?

**Comment by jasonheffner** [comment]
That's correct, I had it backward. The 15:30 meeting should not be displayed. There should only be two meetings for that day then.

What is the fix for the timezones then?

**Comment by jasonheffner** [comment]
I believe this also may be happening with EXDATE

**Comment by u01jmg3** [comment]
Thanks - yes it all goes through `iCalDateToUnixTimestamp()` which needs some tweaking.

**Comment by jasonheffner** [comment]
I attempted a patch to try and return the correct timestamp. This worked on almost all my test files except one, where I believe the recurring event uses a different TZ format. I believe that the recurring events also may need to be parsed by timestamp with the correct conversions possibly with the same function.

[ical.patch.txt](https://github.com/u01jmg3/ics-parser/files/959767/ical.patch.txt)

Here was my php code to display the entries

date_default_timezone_set('America/New_York');
use ICal\ICal;
$ical = new ICal('ical.ics', array(
    'defaultSpan'           => 2,     // Default value
    'defaultWeekStart'      => 'MO',  // Default value
    'skipRecurrence'        => false, // Default value
    'useTimeZoneWithRRules' => false, // Default value
));
$events = $ical->eventsFromRange($dtStartDay, $dtEndDay);

foreach ($events as $event) {

    $dtStart = new \DateTime('now', new \DateTimeZone('America/New_York'));
    $dtEnd = new \DateTime('now', new \DateTimeZone('America/New_York'));
    $dtStart->setTimestamp((int) $ical->iCalDateToUnixTimestamp($event->dtstart));
    $dtEnd->setTimestamp((int) $ical->iCalDateToUnixTimestamp($event->dtend));
    echo sprintf('  <li>%s - %s : %s</li>' . PHP_EOL, $dtStart->format('r'), $dtEnd->format('r'), $event->summary);

}

I believe I might have taken a different approach and not sure if this helps.

**Comment by jasonheffner** [comment]
I was a bit hasty and uploaded an earlier patch file

[ical.patch.txt](https://github.com/u01jmg3/ics-parser/files/959790/ical.patch.txt)

**Comment by u01jmg3** [comment]
Thanks for your efforts - your patch actually crashes my SourceTree but opening in an editor I get the gist of your change. Still working on an effective resolution. Hope to have something soon.

**Comment by jasonheffner** [comment]
The patch I did has been working for a few weeks now, well. The gist of the change is setting the TimeZone first then the time such that the conversions are done properly, inside the datetime object, as compared trying to figure out the time difference afterward and adjusting. You also have to explicitly set the TZ for the TimeDate object as I observed it seems to like to inherit this setting from elsewhere; unfortunately, I don't use TimeDate often enough to know best practice.

**Comment by u01jmg3** [comment]
Wow 16 days has flown by - apologies, I have been away. Will look at this again shortly

**Comment by jasonheffner** [comment]
Here is what I've been running.

https://github.com/jasonheffner/ics-parser/commit/db0049aacd1415bbc2bcf0432f8d1f5894e232db#diff-50681920b8994c51dcfbb9a44850348f

I have one meeting every other week that seems to break with recurrence I still need to look into.

**Comment by u01jmg3** [comment]
Finally made time to look at this. Using your diff I have tailored your code to provide a slightly different fix. The reason being I am dubious whether the time zone should even be applied when [`iCalDateToUnixTimestamp()`](https://github.com/u01jmg3/ics-parser/blob/06275bbe36048bf73754bbc5781ce29852a88535/src/ICal/ICal.php#L556) is called because really its function should only be to convert a datetime to its UNIX timestamp equivalent.

What I was finding before with your example was that the time zone was being re-applied to the `15:30` event when `iCalDateToUnixTimestamp()` was used. This meant it became `11:30` (`-4` hours). This in turn meant the recurrence ID logic that was in place couldn't match correctly and thus you had a duplicate event because the parser did not know the `15:30` event (it saw as `11:30`) should be replaced by the `14:00` one.

See what you think.

---

> _I have one meeting every other week that seems to break with recurrence I still need to look into._

- Is it still present after using the most recent fix (06275bb)?
- Can you provide the iCal for me to debug?

**Comment by jasonheffner** [comment]
Sorry for the delay after the holiday. I took a look at the code and tested it on a Month's worth of past days in April. It's closer but I do believe that you need to set the TimeZone each time for the TimeDate object based on the entry in the ical file. Currently, the code is working "most of the time" but I found a few days where it breaks since the TZ format changes and for some complex rules. 

It's working "relative" to your current TZ. For example, if you are working with everything in the same TZ as your default TZ set it would work fine, but if you are working with dates outside your current TZ, ie DST, then the timestamps returned are incorrect and skewed. If you look at the "timestamp" returned by iCalDateToUnixTimestamp() being your "test" for correctness it is setting the wrong date/time because of the TZ. I believe this is also why I still have some problems with some of the complex recurrences and exclusions for some of our meetings.

**Comment by u01jmg3** [comment]
Thanks - could you provide the test data which you are using?

**Comment by jasonheffner** [comment]
I shared some unedited versions with you to help troubleshoot.

**Comment by u01jmg3** [comment]
Thanks - this will help a lot. Can you point me to a few problematic events and what is wrong with them and what you would expect them to be?

Perhaps a README in the repo with this info would help me out a lot.

**Comment by jasonheffner** [comment]
updated with a readme .. hopefully, illustrates the wrong timestamp set

**Comment by u01jmg3** [comment]
- Been through your examples and made numerous changes in a [separate branch](https://github.com/u01jmg3/ics-parser/compare/issue-129?expand=1) to correct the issues you found
- Gist of it is, you can now get the UNIX timestamp you are looking for when iterating through the events using:

    ```php
    $ical->iCalDateToUnixTimestamp($event->dtstart_array[3], $forceTimeZone = true);
    ```

- I have also corrected the logic for matching recurrence events by making the comparison aware of time zone data - goodbye dupes

**Comment by jasonheffner** [comment]
It's looking good .. the dupes are also gone in the branch which is an extra bonus. I was wondering why the need for the extra config parameter for "forceTimeZone", shouldn't this be done in all cases to have the correct timestamp delivered? If you wanted to force TZ wouldn't that be for overriding the one supplied in the ical file already, meaning the option would be the opposite case? More trying to understand what you are going for.  Perhaps it's just a difference in what we think the default handling should be. You are pulling the TZ out of ical so thought you would want to use it by default.

I tested in a few other dates I noticed dupes and it's working great.

**Comment by u01jmg3** [comment]
Thanks for taking the time to QA

> _I was wondering why the need for the extra config parameter for "forceTimeZone", shouldn't this be done in all cases to have the correct timestamp delivered?_

This is more me being cautious as it has been tricky to nail down time zone logic in the parser with various other issues being raised. Once things are stable I will look to remove but for now I feel happier having it.

> _If you wanted to force TZ wouldn't that be for overriding the one supplied in the iCal file already, meaning the option would be the opposite case?_

You're right - this could become confusing but as above I hope to phase out the parameter once the dust has settled and things become stable. I could rename the variable?

Once you are happy I'll raise a PR and if you have time, could you review and then I will merge in `master`?

**Comment by jasonheffner** [comment]
Makes sense.. and it's easy to switch the default value later. I think the variable name works and I can set it to true for our parsing needs. It corrects all the parsing errors I've seen in the last month. This is the most complete ical parser I found for PHP. I've tried several, all with different problems.

I like how you extended the class to include the TZ. That's the part I hadn't looked closely enough on how you were handling TZ within recurrences; I guess you weren't. I wasn't sure how best to implement that either and like your solution.

**Comment by u01jmg3** [comment]
> _This is the most complete ical parser I found for PHP._

Appreciate the compliment.

---

Cast your eye over PR #142 and see what you think - made some final changes to refactor and improve the code I had already written but essentially it achieves the same thing and addresses the issues you raised.

You may see some code that looks repetitive and not as neat as it could be - at this point I don't want to introduce any breaking changes to the parser but eventually I will bump to `v3.0.0` and take the hit.

**Comment by jasonheffner** [comment]
I went through the changes and only a few comments. I see what you did to the function so altered my code to match instead using the datetime object

```
date_default_timezone_set('America/New_York');

use ICal\ICal;
$ical = new ICal('data.txt', array(
    'defaultSpan'           => 2,     // Default value
    'defaultWeekStart'      => 'MO',  // Default value
    'skipRecurrence'        => false, // Default value
    'useTimeZoneWithRRules' => false, // Default value
));

$events = $ical->eventsFromRange($dtStartDay, $dtEndDay);
$ESTTZ = new DateTimeZone('America/New_York');

foreach ($events as $event) {
    $dtStart = $ical->iCalDateToDateTime($event->dtstart, $forceTimeZone = true);
    $dtEnd = $ical->iCalDateToDateTime($event->dtend, $forceTimeZone = true);
    // Set TZ for display purposes
    $dtStart->setTimezone($ESTTZ);
    $dtEnd->setTimezone($ESTTZ);
```

The setTimezone line [#638](https://github.com/u01jmg3/ics-parser/blob/8860c92b1670d649ef295ca6fe4a3d4b7c7fac11/src/ICal/ICal.php#L638) is really only needed for displaying the DateTime object in your preferred TZ at the end of the routine, as the times were entered into their corresponding TZs further up. I don't think you would need forceUtc and I would instead set it to the default TZ for consistency. You can see in the code above I set the TZ on both objects returned. I had to do this since they were occasionally, not always, coming back in UTC, hence not consistent; if the DateTime returned was always in my default TZ then I wouldn't have to do this for instance. 

I saw quite a bit of repetitive code but never fault anyone for it. I'm a sysadmin so in most cases, it's more important for code to work correctly. I'm figuring at some point you'll go back and clean it up after the bugs and features are addressed.  

To note: I tried a lot of the PHP ical parsers and this is the closest to correctly parsing all the ical features. Each one had it's own issues.. sabre/vobject was the most disappointing as I looked into that one first since GLPI uses it. The sorted eventsFromRange function was exactly what I needed as well. I appreciate the work.

**Comment by u01jmg3** [comment]
> _The setTimezone line [#638](https://github.com/u01jmg3/ics-parser/blob/8860c92b1670d649ef295ca6fe4a3d4b7c7fac11/src/ICal/ICal.php#L638) is really only needed for displaying the DateTime object in your preferred TZ at the end of the routine, as the times were entered into their corresponding TZs further up. I don't think you would need `forceUtc` and I would instead set it to the default TZ for consistency._

This was added because when fixing the issue with the duplicates in your iCal, I found that the `RECURRENCE-ID` dates could be given in different time zones which is not ideal when comparing. I therefore included a `$forceUtc` flag in order to be able to make a comparison across a consistent time zone (UTC) and thus match when an event has been overridden by another in a recurrence set. Hope that makes sense.

> _You can see in the code above I set the TZ on both objects returned. I had to do this since they were occasionally, not always, coming back in UTC, hence not consistent; if the DateTime returned was always in my default TZ then I wouldn't have to do this for instance._

I could add this as a new feature but as above I would have to keep the `$forceUtc` functionality.

> _The sorted eventsFromRange() function was exactly what I needed as well. I appreciate the work._

:+1:

**Comment by jasonheffner** [comment]
Ohh yeah, that makes sense! I was going to suggest "forceUtc or use the default TZ" at first, but now wondering if there could be a use for using the originating TZ from ical; so the current pull works for me. I'll just need to set the TZ after the DateTime is returned; perhaps documentation about setting your display TZ after calling that function? That could confuse folks who aren't familiar with DateTime objects if they aren't consistently returned in the same TZ. I'm assuming that function is preferred over using unixtimestamp since you changed your example.

**Comment by u01jmg3** [comment]
> _perhaps documentation about setting your display TZ after calling that function? That could confuse folks who aren't familiar with DateTime objects if they aren't consistently returned in the same TZ._

I shall update the README and merge in the PR. The parser will use the time zone info given in the iCal so I would expect the source of the iCal to include time zone info throughout for the output to be consistent (some applications are better than others at doing this). And there is always `$event->dtstart_tz` and `$event->dtend_tz` to fallback on.

> _I'm assuming that function is preferred over using a Unix timestamp since you changed your example._

Yes - there are several limitations when using a Unix timestamp (e.g. https://bugs.php.net/bug.php?id=66836) but these are removed when returning a `DateTime` object. For backwards compatibility until I move to `v3.0.0`, `iCalDateToUnixTimestamp()` will still be available but I would recommend moving to `DateTime`.

**Comment by jasonheffner** [comment]
> Would using $ical->iCalDateToDateTime($event->dtstart_array[3], $forceTimeZone = true) prevent you having to apply the time zone?

Unfortunately not, I still get some dates returned in the UTC TZ. I don't mind setting the TZ though and can switch to using iCalDateToDateTime.

**Comment by u01jmg3** [comment]
- Okay - will merge in the PR and close off this issue.
- If at any point you think the parser requires extra functionality to support your needs just raise a new issue and I will assist.
- Thank you for all your help.

**Comment by u01jmg3** [comment]
See #142

**Comment by jasonheffner** [comment]
Ditto!  Thanks for your support.
