### ISSUE TITLE
Multilines in DESCRIPTION are not supported

### ISSUE THREAD

**Issue by caco3** [u01jmg3/ics-parser#132]
DESCRIPTIONS (and maybe other fields) can be on multiple lines.
A 2nd or later line always starts with a whitespace.
Example event:
```
BEGIN:VEVENT
ORGANIZER:MAILTO:info@example.com
SUMMARY:my summary
UID:1234567
DTSTAMP:20170117T102814Z
LAST-MODIFIED:20170117T124845Z
CREATED:20170117T124845Z
DTSTART:20170314T053000Z
DTEND:20170314T063000Z
DESCRIPTION:A very long description split onto multiple lines. The sec
 ond line starts with a whitespace.
END:VEVENT
```
Note that the line break can be within a single word.

The current code only uses the first line of a multiline value.

Patch https://github.com/u01jmg3/ics-parser/pull/131 fixes this.

**Comment by u01jmg3** [comment]
This doesn't appear to be an issue in the latest version of `dev-master`.

<img width="255" alt="demo" src="https://cloud.githubusercontent.com/assets/1266205/25360801/9ddb47fe-2942-11e7-97fd-d7951a514c51.png">

---

> Note: the [quoted MartinThoma commit](https://github.com/MartinThoma/ics-parser/commit/999c628d2447e2a9a20f3704aed2a81b1126149a) is 6 years old

**Comment by caco3** [comment]
I can't see any other branches beside master!

**Comment by u01jmg3** [comment]
Are you familiar with [Composer](https://getcomposer.org/doc/articles/aliases.md#branch-alias)?

**Comment by caco3** [comment]
hmm, no, sry, didn't know about that. I can't really understand its purpose, since normal branches also would work. Beside of that, as I understand, only you have access to that dev-master, so I couldn't test it myself.
Anyway. I fixed it for myself and wanted to give you a fix. Use it or leave it.

**Comment by u01jmg3** [comment]
> _hmm, no, sry, didn't know about that. I can't really understand its purpose, since normal branches also would work._

- [Composer](https://getcomposer.org/doc/00-intro.md#introduction) is a tool for dependency management in PHP.
   - It allows you to declare the libraries your project depends on and it will manage (install/update) them for you.

> _Beside of that, as I understand, only you have access to that dev-master, so I couldn't test it myself._

- That is not correct; `dev-master` is an alias for using with Composer that is open for anyone to use in place of a specific release version (e.g. `2.0.5`). 
- As per the [Composer documentation](https://getcomposer.org/doc/articles/aliases.md#branch-alias), `dev-master` allows you to use the latest code from a repository's `master` branch which for this project will contain the latest code including the most recent fixes.

> _Anyway. I fixed it for myself and wanted to give you a fix. Use it or leave it._

- I am happy to use your code but first I have to reproduce your issue.
- As per the above screenshot, the parser correctly handles the iCal you provided.
- I therefore cannot merge your code until I can reproduce your issue.
