### ISSUE TITLE
Default timezone doesn't get set when filename isn't specified

### ISSUE THREAD

**Issue by ruskiyos** [u01jmg3/ics-parser#133]
Issue: 
Event parsing fails if `defaultTimeZone` property doesn't get set.

Cause: 
If a filename is not specified during constructor, the `defaultTimeZone` property doesn't get set

https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L179

    // ICal.php
    public function __construct($filename = false, array $settings = array()) {
        if (!$filename) {
            return false;
        }
        ...
        $this->defaultTimeZone = date_default_timezone_get();
        ...
    }

As you can see, if a `$filename` isn't specified, the property `defaultTimeZone` doesn't get set. As a result, event parsing fails later on, because `defaultTimeZone` is `null`
https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L534

    $date = new \DateTime($icalDate, new \DateTimeZone($this->defaultTimeZone));

I noticed in the readme that `defaultTimeZone` cannot by customized. 
Why force it to the ini and not allow `defaultTimeZone` to be customizable? What if I want to import events under a specific timezone?

**Comment by u01jmg3** [comment]
Thanks for raising this - I am already working on improving the functionality behind `defaultTimeZone` and you are correct with everything you have said

**Comment by u01jmg3** [comment]
Thanks for raising this issue - I shall fix the bug

The time zone can be set using `date_default_timezone_set()` [(as per the example)](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L5) allowing it to be customizable

**Comment by ruskiyos** [comment]
The problem with customizing it with `date_default_timezone_set()` is that the configuration change is applied to the entire lifecycle of the php script. If I have different parts of the app that rely on `date_default_timezone_get()` to get the actual timezone, but I need to import an iCAL under a "specific" timezone, then it results in unnecessary code.
 
I have to temporarily save the default timezone, change the default timezone to the timezone that I need, import the calendar, and restore the original default timezone.
Why not just allow it to be passed in through the config?

**Comment by u01jmg3** [comment]
Let me think about this - initially I had things set up as you describe albeit the user could not override the setting. Then I switched to using `date_default_timezone_get()`. I do get your point though.

**Comment by u01jmg3** [comment]
Let me know if you have any more issues
