### ISSUE TITLE
FreeBusy Event Error

### ISSUE THREAD

**Issue by ArthurProvost** [u01jmg3/ics-parser#134]
### Description of the Issue:
I'm currently trying to parse an ifb(FreeBusy) file using your librairy, without success.
Indeed, i'm working with a local ifb file named 'filefb2.ifb', which contains 4 events (that you can see below);
When I code this:

```php
$ical = new ICal('filefb2.ifb');
$array= $ical->freeBusyEvents();
print_r($array);
```

The result is contains only:  `[FREEBUSY] => 20170716T131500Z/20170516T100500Z`,
which is the last free busy event of my file. but the first ones disappeared. 

### My IFB file:

```
BEGIN:VCALENDAR
PRODID:Zimbra-Calendar-Provider
VERSION:2.0
METHOD:PUBLISH
BEGIN:VFREEBUSY
ORGANIZER:mailto:aprovost@insa-rennes.fr
DTSTAMP:20170316T204607Z
DTSTART:20170213T204607Z
DTEND:20180517T204607Z
URL:http://zstore2.insa-rennes.fr:8080/service/home/aprovost@insa-rennes.fr?fmt=ifb
FREEBUSY;FBTYPE=BUSY:20170623T070000Z/20170223T110000Z
FREEBUSY;FBTYPE=BUSY:20170624T131500Z/20170316T151500Z
FREEBUSY;FBTYPE=BUSY:20170715T131500Z/20170416T150000Z
FREEBUSY;FBTYPE=BUSY:20170716T131500Z/20170516T100500Z
END:VFREEBUSY
END:VCALENDAR
```

**Comment by u01jmg3** [comment]
Let me know if you have any more issues
