### ISSUE TITLE
Feature: Support BYSETPOS in MONTHLY rrule's

### ISSUE THREAD

**Issue by coreation** [u01jmg3/ics-parser#136]
### Description of the Issue: 

As described on #15 it seems that the functionality of using BYSETPOS in a MONTHLY recurring rule is not yet implemented.

### Steps to Reproduce:
`FREQ=MONTHLY;BYSETPOS=3;BYDAY=MO;INTERVAL=1` would be an example of an occurrence rule.

As I'm not yet that familiar with the code, in the monthly recurrence where BYDAY is handled, it seems that in the do-while statement, the next week is passed as the next timestamp to apply the rule on. I'm not sure @u01jmg3 why this is the case, is this to support some rule that says every friday of the month? I'm throwing a wild guess out there, but if BYSETPOS is passed, we already know it's not going to be a weekly recurring event in that month, but a one-off event? Would that be sufficient to only run the do-while once per month instead of incrementing it per week?

**Comment by u01jmg3** [comment]
> ... _Would that be sufficient to only run the do-while once per month instead of incrementing it per week?_

Yep, it would be and is what I have done to fix the problem. 👍

**Comment by coreation** [comment]
Awesome, in what branch was this merged into? I'd like to take it out for a spin ;)

**Comment by u01jmg3** [comment]
I shall create a new release after a few more things have been fixed - until then `dev-master` (if new features are required) is your only choice, I am afraid.

**Comment by coreation** [comment]
@u01jmg3 thanks for the quick reply! dev-master it is then, looking forward for the release ;)
