### ISSUE TITLE
Raise an exception when the file doesn't exists

### ISSUE THREAD

**Issue by Zeyckler** [u01jmg3/ics-parser#138]
### Description of the Issue:

When you execute `new ICal($filename)` with a non-existing file/URL, the function of `initLines` inside the constructor will fail. So I think that the constructor needs to check that the function of `file(...)` is not returning false, and in that case, throw an exception.

Right now I'm using the library in a batch process, so to avoid wrong URLs I need to do a GET request to know if the URL is valid and then create the `new ICal($url)`, if the library raised the exception about the invalid/wrong URL/path I could avoid the previous request.

### Steps to Reproduce:

1) Create a `new ICal($filename)` with a non-existing file/URL
2) The function of `initLines` inside the constructor will fail

**Comment by u01jmg3** [comment]
As the constructor allows a file, a URL or an array of iCal content, instead I suggest using the following to batch process your iCal files:

```php
$ical = new ICal();
$ical->initUrl('https://raw.githubusercontent.com/u01jmg3/ics-parser/master/examples/ICal.ics');
```

If the URL is invalid an appropriate error will now be thrown.

**Comment by Zeyckler** [comment]
Thanks @u01jmg3 for the response. The problem with that is that if the URL doesn't exists (or is returning a HTTP error like 404 or 403) and you are in a batch process you can't do a try/catch block, for example, to log the error.

**Comment by Zeyckler** [comment]
That https://github.com/u01jmg3/ics-parser/commit/4fc6369bbf91a66cdb49f5bfb04c6ad00a9a9437 is  what I want. :D Thanks!
