### ISSUE TITLE
Parser does not get Attendees

### ISSUE THREAD

**Issue by MarioCodes** [u01jmg3/ics-parser#140]
### Description of the Issue:
I don't know why but when I ini the parser with a full String containing all the information needed, it's not saving the Attendees and this information is lost. It saves however the organiser mail.

### Steps to Reproduce:
Ini the parser with [string.txt](https://github.com/u01jmg3/ics-parser/files/1038603/string.txt) and output  with `printData()`.

ex:

```php
$string = ... ; (contains the exact same text uploaded)
$ical = new ICal();
$ical->initString($string);

foreach($ical->events() as $event) echo $event->printData();
```

### Result:
The resulting output for an example affected event (which has attendees) is:

SUMMARY: 2 weeks event
DTSTART: 20170507T000000
DTEND: 20170516T000000
DTSTART_TZ: 20170507T020000
DTEND_TZ: 20170516T020000
DTSTAMP: 20170529T153758
UID: V9XV56RQGUUCC0H8C39CP
CREATED: 20170529T153758
STATUS: CONFIRMED
ORGANISER: MAILTO:praktikum@gmail.de

And if I comment the line 168 in EventObject.php (the array_filter to remove blank values):

SUMMARY: 2 weeks event
DTSTART: 20170507T000000
DTEND: 20170516T000000
DTSTART_TZ: 20170507T020000
DTEND_TZ: 20170516T020000
DURATION:
DTSTAMP: 20170529T153758
UID: V9XV56RQGUUCC0H8C39CP
CREATED: 20170529T153758
LAST-MODIFIED:
DESCRIPTION:
LOCATION:
SEQUENCE:
STATUS: CONFIRMED
TRANSP:
ORGANISER: MAILTO:praktikum@gmail.de
ATTENDEE(S): 

They're empty even tho in the original string it did contain the attendees. What am I doing wrong or why is it not parsing them?

**Comment by u01jmg3** [comment]
The `string.txt` provided is [not valid iCal](https://icalendar.org/validator.html) - in order to debug fully I would need a valid `.ics` file. Also the file appears to contain 12 calendars - usually I would expect only 1.

From what I can determine, the reason for a lack of attendees unlike organisers is due to the attendee data not being stored under the attendee property. Instead it looks to be under the uncommon property called `X-NC-GROUP-ID` which the parser does not support.

**Comment by MarioCodes** [comment]
Found the issue, it was not your parser. Sorry.

Next Cloud adds an space and a line break every 75 chars when obtaining an export through .ics or as a string when connecting directly. Even when it breaks in half a string or parameters; it broke the whole file. Removing those two chars, the parser gets correctly all the info.

The 12 calendars is the way the client I'm using exports the data, every event in it's own calendar.

Just so you know even tho the ATTENDEES are under the property X-NC-GROUP-ID, your parser is getting the info and setting them under the ATTENDEES property correctly.

Thanks.

**Comment by u01jmg3** [comment]
Thanks for getting back to me - as I said it was quite difficult to debug with the file that you provided but I am glad that you found a resolution and that the parser is working as expected.
