### ISSUE TITLE
Support request: .ics files generated by outlook have a per line character count of 76, resulting in information being excluded, specifically attendees

### ISSUE THREAD

**Issue by clrockwell79** [u01jmg3/ics-parser#141]
I checked for how to properly submit support tickets and I don't see any instructions, apologies if this is the incorrect place.

As the title says, I am dealing with outlook generated .ics files (attaching one that has the email addresses changed; however, I made sure to retain the exact character count) that break to new lines at 76 characters.  This results in an ATTENDEE looking like:
```
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=chris@chri
 srockwell.com:MAILTO:chris@chrisrockwell.com
```
The parser is ignoring all attendees and EventObject::attendee is null.  Is there something I need to do to account for this?

I am parsing the files on OSx, php 7.0.15
[invite_new.txt](https://github.com/u01jmg3/ics-parser/files/1048465/invite_new.txt)

**Comment by clrockwell79** [comment]
Sorry.  The `Issue-129` branch has different code for `unfold` and that has solved my issue.

**Comment by u01jmg3** [comment]
> _I checked for how to properly submit support tickets and I don't see any instructions, apologies if this is the incorrect place._

- As you have done, the issue tracker is the correct place to raise a ticket.
  - This is common practice for many open source projects on GitHub
- It is also useful to read the [contribution guidelines](https://github.com/u01jmg3/ics-parser/blob/master/.github/CONTRIBUTING.md) for this project and to utilise the [new issue template](https://github.com/u01jmg3/ics-parser/issues/new) when drafting a new issue.

> _The `issue-129` branch has different code for `unfold()` and that has solved my issue._

Glad you got it sorted but the code for `unfold()` is the same in `issue-129` branch as it is in the `master` branch. I can only think you were using the `v2.0.5` release and not `dev-master`.
