### ISSUE TITLE
Importing iCal from an HTTPS source

### ISSUE THREAD

**Issue by barryguk** [u01jmg3/ics-parser#143]
Hello,

Sorry if this is a stupid question but your code work really well. Thank you.
I just can't seem to get it to work when I provide an https address, it fails with  the following.
Could you let me know what I am missing.
Thank you very much
Great work!
Barry

```
exception 'ErrorException' with message 'file(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in C:\Users\barry\OneDrive\Documents\My Web Sites\SOD site\owners_ical\ICal.php:133
Stack trace:
#0 [internal function]: exception_error_handler(2, 'file(): SSL ope...', 'C:\\Users\\barry\\...', 133, Array)
#1 C:\Users\barry\OneDrive\Documents\My Web Sites\SOD site\owners_ical\ICal.php(133): file('https://www.sim...', 6)
#2 C:\Users\barry\OneDrive\Documents\My Web Sites\SOD site\owners_ical\ical_sync.php(62): ICal\ICal->__construct('https://www.sim...')
#3 {main}
```

**Comment by u01jmg3** [comment]
- Are you using cURL? Sounds like a possible problem with your CA cert in your local setup. Lots on [Google/StackOverflow](https://goo.gl/R1yYfh) about fixing this problem
- The iCal example works swapping to an HTTPS source so I believe this is localized to your machine
- Please check you are using the latest release (`v2.0.6`)

**Comment by barryguk** [comment]
Thank you :)
