### ISSUE TITLE
Setting TZID when not a valid timezone

### ISSUE THREAD

**Issue by munkex** [u01jmg3/ics-parser#146]
Hello,

I noticed that office365 outlook calendar are using there own timezone formats (eg. Romance Standard Time) which aint a valid timezone when using new DateTimeZone..
This created a error when trying to run your parser, so i modified it a little to fix this (might be a smarter way to do this)

at line 688 where you have the // Force time zone with the following code:

```php
if (isset($dateArray[0]['TZID'])) {
   $dateTime->setTimezone(new \DateTimeZone($dateArray[0]['TZID']));
}
```

I added the following to the check of the time zone:

```php
if (isset($dateArray[0]['TZID'])) {
    if(in_array($dateArray[0]['TZID'], timezone_identifiers_list()))
    {
        $dateTime->setTimezone(new \DateTimeZone($dateArray[0]['TZID']));
    } else {
        $dateTime->setTimezone(new \DateTimeZone('UTC'));
    }
}
```

**Comment by u01jmg3** [comment]
Can you provide an iCal file example?

**Comment by munkex** [comment]
Here you go:
http://martin.phpserver.dk/test_office365_outlook.ics

**Comment by u01jmg3** [comment]
- Running the parser against the provided iCal produces no errors for me.
- What error are you experiencing?
- There is already [a function](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1742) in place to check for valid time zones.

**Comment by munkex** [comment]
this is the error im getting:


Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Romance Standard Time)' on line 691

**Comment by u01jmg3** [comment]
- Are you running the latest version of the parser? Try `dev-master`.
- Failing that I need to know how you are loading the parser because I am unable to reproduce the error you are seeing using just the provided iCal.

**Comment by munkex** [comment]
seems like it got fixed with the update you made a few hours ago
