### ISSUE TITLE
Issue with some calendars not showing correct DTSTART_TZ

### ISSUE THREAD

**Issue by munkex** [u01jmg3/ics-parser#148]
Hello again,
Not sure if this is the correct place to put it, but hopefully it is an issue and not just us doing something wrong.

not sure again if we are doing something wrong here.
but we have the following url, your test file modified with a google calendar (you can see the google calendar link inside the url),

when running through your parser it says the 

```
Test i morgen (28-06-2017 06:30)
DTSTART: 20170628T063000Z
DTSTART_TZ: 20170628T043000
```

which should have been:
DTSTART_TZ: 20170628T083000 because we are 2 hours ahead of UTC not 2 hours behind.

http://martin.phpserver.dk/test.php

**Comment by bairdj** [comment]
Can this fix be released? Currently I'm having to reference the specific commit in composer.json to fix my app

**Comment by u01jmg3** [comment]
See [`v2.0.7`](https://github.com/u01jmg3/ics-parser/releases/tag/v2.0.7)
