### ISSUE TITLE
Limit the number of events that are parsed

### ISSUE THREAD

**Issue by munkex** [u01jmg3/ics-parser#149]
We had some files which contained 70k+ events, which made the progress timeout when running through the parser.

So in the function `initLines` we added a counter which broke the progress if we hit that limit.

After the foreach loop we added:

What we thought would be a nice feature if you were able to add so the limit (30 in our case) were able to be changed when initializing the iCal function (default should be unlimited: 0)

Example of use could be something like this:

I attached screenshot of what I were thinking. (I'm not sure if the things are added at the correct places in the file, but it was to give you an example).

![function_initlines](https://user-images.githubusercontent.com/2952180/27726473-efb60192-5d7a-11e7-8089-3c8301c8aab2.png)
![option](https://user-images.githubusercontent.com/2952180/27726474-efb9007c-5d7a-11e7-8617-9da7409dd927.png)

**Comment by munkex** [comment]
Hey,
We noticed a thing that got to do with what i suggested here.

It seems like the $ical->eventsFromInterval('52 week'); dosent only take the first 52 weeks for reoccuring events.
So it would be a nice feature  when limiting events that it also takes into account the amount of reoccuring events.

We noticed it because we have a file with 70k plus events.. wich takes forever to load even when only collecting for the next 52 weeks :) (We can send you this file on a email if you want to have some large file to test with).

**Comment by u01jmg3** [comment]
Apologies for the delay - happy to receive the file. Can you share via a private repo?

**Comment by u01jmg3** [comment]
See my comment here: https://github.com/u01jmg3/ics-parser/issues/182#issuecomment-419705474

**Comment by u01jmg3** [comment]
Closing and will instead manage in #182

**Comment by u01jmg3** [comment]
Fixed by #190 (#184)
