### ISSUE TITLE
Support ability to parse multiple days in MONTHLY BYDAY

### ISSUE THREAD

**Issue by u01jmg3** [u01jmg3/ics-parser#15]
- For example:
  - `FREQ=MONTHLY;BYDAY=2MO,3TU;COUNT=10`
    - Every month on the 2nd Monday and 3rd Tuesday for 10 times

**Comment by coreation** [comment]
I found that FREQ=MONTHLY;BYSETPOS=3;BYDAY=MO;INTERVAL=1 also doesn't work, seems like it's adding it on every monday, instead of every third monday. Is that the same issue?

**Comment by u01jmg3** [comment]
Nope, not the same thing. Your rule does not mention multiple days as it refers only to Monday. Also, this is not an issue but more a reminder of a piece of functionality that has not yet been implemented.

If you're having a problem I would suggest opening a new issue and I would be happy to investigate.

**Comment by coreation** [comment]
Aha, so the rule "first monday of the month, for the coming 3 months" has not yet been implemented? If so I'll open a new issue for this, any pointers on where I can get started to implement this, to get a grasp of how much work this would be? I'm guessing it all happens in the large switch/case corpus where "monthly" is being parsed.

**Comment by u01jmg3** [comment]
> _Aha, so the rule "first monday of the month, for the coming 3 months" has not yet been implemented?_

Nope, not correct; the feature of **supporting multiple days in a MONTHLY BYDAY recurrence rule** has not been implemented yet (aka this issue and its description).

> _"first monday of the month, for the coming 3 months"_

To be clear, the rule you have given (`FREQ=MONTHLY;BYSETPOS=3;BYDAY=MO;INTERVAL=1`) is not the same as the definition you have stated here. Instead it is defined as "every third Monday of the month". As you have spotted, there is a bug with the parser handling this scenario. I shall address this in #136.

**Comment by coreation** [comment]
Yes indeed that RRULE was the third monday, I misleadingly (and unknowingly) used a different example. Thanks for checking and replying on the other issue!

**Comment by u01jmg3** [comment]
The addition of a new library may be overkill for supporting multiple days in a MONTHLY BYDAY recurrence rule. Looking at this library it can be accomplished in [28 lines of code](https://github.com/rlanvin/php-rrule/blob/master/src/RRule.php#L364-L392).

However, this library does appear to have good coverage of RFC 5545 but if it was to be used I would like to see it replace all recurrence processing in ICS Parser to make best use of having the library.

(Note: this ticket is a feature request rather than fixing a bug)
