### ISSUE TITLE
Add support for multi-line descriptions

### ISSUE THREAD

**Issue by kelsey9649** [u01jmg3/ics-parser#150]
- PHP Version: `5.6.30`
- PHP date.timezone: `America/Chicago`

### Description of the Issue:
When parsing in events, the description only provides the first line of the multi-line `DESCRIPTION`. This issue serves as a request for multi-line `DESCRIPTION` support specifically. Not sure if this would be applicable to other fields.

### Steps to Reproduce:
```
BEGIN:VCALENDAR
PRODID;X-RICAL-TZSOURCE=TZINFO:-//Airbnb Inc//Hosting Calendar 0.8.8//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
DTEND;VALUE=DATE:20160805
DTSTART;VALUE=DATE:20160802
UID:r3a12hp6txia-ay5pye4efd6a@airbnb.com
DESCRIPTION:CHECKIN: 08/02/2016\nCHECKOUT: 08/05/2016\nNIGHTS: 3\nPHONE: 
 +1 (720) 236-0559\nEMAIL: (no email alias available)\nPROPERTY: Great 2b
 d Apartment in a Nice Area\n
SUMMARY:Guest Person (ABCDEF)
LOCATION:Great 2bd Apartment in a Nice Area
END:VEVENT
END:VCALENDAR
```

**Comment by u01jmg3** [comment]
The parser already does support this:

<img width="470" alt="demo" src="https://user-images.githubusercontent.com/1266205/28038957-9194236e-65b8-11e7-9ee8-b146aac22ee2.png">

**Comment by kelsey9649** [comment]
Just checking, are you running v2.0.6 and getting those results?

**Comment by u01jmg3** [comment]
`dev-master` but it has nothing new that would affect parsing multi-line content.

Are you on a Mac by any chance?

**Comment by kelsey9649** [comment]
No mac on this side. Application is in a Vagrant VM, Ubuntu 14.04. I'll run the example and see if I get the same results.

**Comment by kelsey9649** [comment]
HTML generated by placing the AirBnB iCal into the example `iCal.ics` and running it:

```        <div class="clearfix visible-md-block"></div>                    <div class="col-md-4">
            <div class="thumbnail">
                <div class="caption">
                    <h3>Glenda Flynn (HMHTDH544M) (06-09-2017 00:00)</h3>
                    <p>SUMMARY: Glenda Flynn (HMHTDH544M)</p><p>DTSTART: 20170906</p><p>DTEND: 20170909</p><p>DTSTART_TZ: 20170906T000000</p><p>DTEND_TZ: 20170909T000000</p><p>UID: r3a12hp6txia-uo58gkanqx4n@airbnb.com</p><p>DESCRIPTION: CHECKIN: 09/06/2017
CHECKOUT: 09/09/2017
NIGHTS: 3
PHONE:</p><p>LOCATION: Great 2bd Apartment in a Nice Area</p>                </div>
            </div>
```
and a screenshot showing the output, file used for the iCal data, and the composer path to it:

![image](https://user-images.githubusercontent.com/722417/28041116-ca2ed456-658d-11e7-87b4-f3d2bd5af278.png)

**Comment by u01jmg3** [comment]
You are going to have to provide me with the actual ICS file as I cannot reproduce the issue you are having without it. I suspect it has something to do with line endings.

**Comment by kelsey9649** [comment]
The iCal feed is accessible at https://www.airbnb.com/calendar/ical/11009370.ics?s=76a0a14d1e7a2477dce3c3a9dec558fe and the hidden characters look like this in Notepad++ (showing all symbols):

![image](https://user-images.githubusercontent.com/722417/28041480-3853b66c-658f-11e7-9564-a5393dcf7351.png)

That should give you a good idea of the structure and encoding AirBnB is using. You don't have to triage this much if you would like. I was going to debug the library later and find the issue and put a MR up for it. If you aren't busy, feel free though. It is appreciated.

**Comment by u01jmg3** [comment]
Just tried the feed you have provided and it works on my side (including the original event you specified for A. Hudson).

The parser does make use of `PHP_EOL` within an [`unfold()`](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L390) function so that would be the place to start.

Without being able to reproduce your issue (I have no access to a Linux machine) I cannot provide a fix.

**Comment by kelsey9649** [comment]
No problem. I'll determine what is causing it on my side and hopefully find a solution I can provide to the project to help others avoid whatever it is. Thanks!

**Comment by kelsey9649** [comment]
Looks like `keyValueFromString($text)` is the culprit. `addCalendarComponentWithKeyAndValue($component, $keyword, $value)` uses the last keywork if a keyword does not exist. The `$keyword` comes from `keyValueFromString($text)`'s return value. When processing another line of the description such as ``` +1 (720) 236-0559\nEMAIL: (no email alias available)\nPROPERTY: Great 2b``` the aforementioned method attempts a match on line 438. The regex is not matched and returns false. `$add` becomes false and `$keyword` becomes null since false is not an array. `$values` becomes null as well. The line is then ignored. I may defer to you for a proposed solution as my understanding of the library as a whole is limited.

**Comment by u01jmg3** [comment]
Do you have access to test on a Windows machine? Good explanation of the problem but the issue is localised to your setup so will likely be a line ending issue at a guess. Happy to assist with a solution once I know the issue.

**Comment by kelsey9649** [comment]
Using 
```
return [
    false,
    $text
]; // Ignore this match
```
at ICal.php:485 in place of `return false` results in records that look like:

```
CHECKIN: 09/06/2017
CHECKOUT: 09/09/2017
NIGHTS: 3
PHONE:, +1 (509) 770-0354
EMAIL: glenda-gex3j0fleed1nkhj@guest.airbnb.com
PROP, ERTY: Great 2bd Apartment in a Nice Area
```

Some oddly placed commas, but it fed it all in. Step in the right direction. I run Windows but I am not in the practice of running PHP on Windows. I would not know what all to do. I just operate on Linux/Unix.

**Comment by u01jmg3** [comment]
The key is getting the unfold function to work correctly - you are too far down the processing stack to correct the problem.

Dump what `unfold()` returns focussing on just the event you gave when opening this issue.

I get:

```
..\ics-parser\src\ICal\ICal.php:396:
array (size=13)
  0 => string 'BEGIN:VCALENDAR' (length=15)
  1 => string 'PRODID;X-RICAL-TZSOURCE=TZINFO:-//Airbnb Inc//Hosting Calendar 0.8.8//EN' (length=72)
  2 => string 'CALSCALE:GREGORIAN' (length=18)
  3 => string 'VERSION:2.0' (length=11)
  4 => string 'BEGIN:VEVENT' (length=12)
  5 => string 'DTEND;VALUE=DATE:20160805' (length=25)
  6 => string 'DTSTART;VALUE=DATE:20160802' (length=27)
  7 => string 'UID:-xns6whnuw8js-56b5losd7v0k@airbnb.com' (length=41)
  8 => string 'DESCRIPTION:CHECKIN: 02-08-2016\nCHECKOUT: 05-08-2016\nNIGHTS: 3\nPHONE: +1 (720) 236-0559\nEMAIL: (no email alias available)\nPROPERTY: Great 2bd Apartment in a Nice Area\n' (length=173)
  9 => string 'SUMMARY:Angela Hudson (MZNRNS)' (length=30)
  10 => string 'LOCATION:Great 2bd Apartment in a Nice Area' (length=43)
  11 => string 'END:VEVENT' (length=10)
  12 => string 'END:VCALENDAR' (length=13)
```

And as you can see at `8`, the whole of the DESCRIPTION has been parsed which will mean subsequent functions used further on in the parser (such as `keyValueFromString()`, etc.) will work as expected.

---

PHP is simple enough to set up on Windows using something like [WAMP](https://sourceforge.net/projects/wampserver/) or [XAMPP](https://sourceforge.net/projects/xampp/).

**Comment by kelsey9649** [comment]
That makes a lot of sense. Looking at ICal.php:198 (in the `unfold($lines)` method), your replacements handle Windows-based CRLF style line endings but not Unix style LF endings. I would propose changing
```
$string = str_replace(array("\r\n ", "\r\n\t"), '', $string);
```
to
```
$string = str_replace(array("\r\n ", "\r\n\t", "\n "), '', $string);
```
This change should add Linux/Unix support to the unfold method. Debugging, the lines look good with that:

![image](https://user-images.githubusercontent.com/722417/28071744-6ebb0e62-6616-11e7-9295-e89095309c78.png)

**Comment by kelsey9649** [comment]
I might also mention, classic Mac line endings are "\r". For cross-platform compatibility it might be good to add that as well.

**Comment by u01jmg3** [comment]
Thanks - I shall make a fix later today

**Comment by u01jmg3** [comment]
Thanks for getting back to me - for any library I would always pull in `dev-master` in case the issue has already been fixed
