### ISSUE TITLE
Duplicate event for a single exception of a recurring event

### ISSUE THREAD

**Issue by vungyn** [u01jmg3/ics-parser#154]
- PHP Version: `5.6.23`
- PHP date.timezone: `Europe/Berlin`
- ICS Parser Version: `2.0.6`
- Mac

### Description of the Issue:
A duplicate event is showing for a single instance of a recurring event. Don't think it's related to #129. The only difference in the exception is added location detail. Time and date are the same.

### Steps to Reproduce:
Example file from Google Calendar. On 13/08/2017 there should only be one event, however two events are returned.

[test.ics](https://github.com/u01jmg3/ics-parser/files/1211372/test.txt)

**Comment by vungyn** [comment]
I don't think the fix is working correctly. Only the first (exception) instance should have the location, the next ones shouldn't as per the parent event.

That being said, the fix isn't working at all using my Google calendar link, it still shows the duplicate event.

https://calendar.google.com/calendar/ical/tnttvictoria.org_co2nuvlisb463gtakhb6nddaqs%40group.calendar.google.com/public/basic.ics

**Comment by u01jmg3** [comment]
> _I don't think the fix is working correctly. Only the first (exception) instance should have the location, the next ones shouldn't as per the parent event._

There is a limitation on the current implementation of the library whereby all recurrence events mirror the initial parent event. If you change that parent event then all subsequent (child) recurrence events will have those changes also. This is the scenario with your data. I agree it is not ideal nor entirely correct. I am pondering how to overcome this issue without having to make  major changes to the parser (something which I do not currently have time to do.)

> _That being said, the fix isn't working at all using my Google calendar link, it still shows the duplicate event._

Mistake on my behalf now corrected.
