### ISSUE TITLE
Issue Parsing https://www.trumba.com ics feed

### ISSUE THREAD

**Issue by spib** [u01jmg3/ics-parser#158]
- PHP Version: `7.1.0`
- PHP date.timezone: `[Country]/[City]`
- ICS Parser Version: `dev-master`
- Mac

### Description of the Issue:
Trumba provides an ICS export of their calendar data. They use an number of custom fields in the format shown below

`X-TRUMBA-CUSTOMFIELD;NAME="Event Type";ID=21;TYPE=number:Arts &amp\; Culture`

The ICal parser doesn't support this too well, firstly because it doesn't recognize the multiple values in the one field. For example, the output from `var_dump($event->x_trumba_customfield)` for the line above is

    string(22) "Arts &amp;amp; Culture"

And the output from `var_dump($event->x_trumba_customfield_array)` is

    array(2) {
      [0]=>
      array(1) {
        ["NAME"]=>
        string(13) "Event Type;ID"
      }
      [1]=>
      string(22) "Arts &amp;amp; Culture"
    }

Secondly, trumba includes multiple `X-TRUMBA-CUSTOMFIELD` fields per `VEVENT`, with the `NAME` providing the uniqueness. It would awesome if the output from `var_dump($event->x_trumba_customfield_array)` was something like

      array(1) {
      [0]=>
      array(1) {
        ["NAME"]=>
        string(13) "Event Type"
        ["ID"]=>
        string(2) "21"
        ["TYPE"]=>
        string(6) "number"
        ["VALUE"]=>
        string(19) "Arts &amp\; Culture"
      }
    }

### Steps to Reproduce:

See attached trumba.ics.txt

[trumba.ics.txt](https://github.com/u01jmg3/ics-parser/files/1245335/trumba.ics.txt)

**Comment by spib** [comment]
Hi,

Wondered if you could point me towards a solution for this? Where in the parser should I look?

Many Thanks

James

**Comment by u01jmg3** [comment]
This would be brand new functionality. I only have time to fix bugs so that is why this is on hold. Well structured PRs are welcome.

Take a look at how the calendar name is retrieved: [`calendarName()`](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1644).

**Comment by u01jmg3** [comment]
Closing due to a lack of activity. Happy to re-open.
