### ISSUE TITLE
EXDATES (UTC) not removing occurrence (local time)

### ISSUE THREAD

**Issue by cbcsouthlake** [u01jmg3/ics-parser#161]
### Issue:
I am trying to parse an ical feed from a third-party vendor.  They are sending the start and end times in the timezone "America/Chicago", but the EXDATEs in Zulu (UTC) time.  The EXDATEs are not being removed by the parser.  Is the timezone differential to blame here?  If so, how can I fix this?  I have tried every combination of config on defaultTimeZone, useTimeZoneWithRRules, and $forceTimeZone  without any luck.

### Config:
PHP 7.1.6
Default Timezone: America/Chicago
ICS Parser Version: 2.0.7
Mac

### Sample ical:
```
BEGIN:VEVENT
SUMMARY:Cross Culture
DESCRIPTION:Group: Cross Culture Calendar\nCampus: Countryside Bible Church
 \nBible study and fellowship for high school students&nbsp\;in grades 9-12
 .
LOCATION:Gymnasium\, 250 Countryside Ct\, Southlake\, Texas 76092
CREATED:20170522T183604Z
LAST-MODIFIED:20170908T000805Z
DTSTAMP:20170908T000805Z
SEQUENCE:1505760921
UID:71192-15@ccbchurch.com
DTSTART;TZID=America/Chicago:20170503T190000
DTEND;TZID=America/Chicago:20170503T210000
RRULE:FREQ=WEEKLY;BYDAY=WE;WKST=SU
EXDATE:20170601T000000Z
EXDATE:20170803T000000Z
EXDATE:20170824T000000Z
EXDATE:20171026T000000Z
EXDATE:20171102T000000Z
EXDATE:20171123T010000Z
EXDATE:20171221T010000Z
EXDATE:20180104T010000Z
EXDATE:20180215T010000Z
EXDATE:20180531T000000Z
EXDATE:20180614T000000Z
EXDATE:20180621T000000Z
EXDATE:20180809T000000Z
EXDATE:20180823T000000Z
END:VEVENT
```

### Sample init/iteration:
```
use ICal\ICal;
function events_array(){
try {
    $ical = new ICal('iCal.ics', array(
        'defaultSpan'           => 1,     // Default value
        'defaultTimeZone'       => 'America/Chicago', 
        'defaultWeekStart'      => 'SU',  // Default value
        'skipRecurrence'        => false, // Default value
        'useTimeZoneWithRRules' => false, // Default value
    ));
} catch (\Exception $e) {
    die($e);
}

$forceTimeZone = false;

$events = $ical->events();
```

**Comment by cbcsouthlake** [comment]
I just noticed that on each occurrence the following config is listed:
```
"defaultTimeZone": null,
"defaultWeekStart": "MO",
"skipRecurrence": false,
"useTimeZoneWithRRules": false,
```
This never changes regardless of the config values I enter when instantiating ICal.  Am I setting up wrong somehow?

**Comment by u01jmg3** [comment]
_RE: your first comment and issue_

Looking at your data, you have a weekly rule that generates an event for Wednesday @ 7-9pm. However, all 13 exdates listed fall on a Thursday (not on a Wednesday). As well as this, as you have spotted, the exdates are defined using the Zulu time zone whereas the recurrence event is defined with the `America/Chicago` time zone. There is therefore no way for the parser to match your exdates with any of the generated recurrence events no matter what config is used.

If it wasn't for the exdates falling on a Thursday, I might have been able to look at a solution but I am not sure that your data is correct.

_RE: your second comment_

The config is working correctly but as you have spotted the Event class is not inheriting the custom values passed into the ICal class (one extends the other). This won't affect your issue but I will look to correct.

**Comment by cbcsouthlake** [comment]
The trouble is 7:00 pm on Wednesday in America/Chicago IS 12:00 am on Thursday in UTC.  Is there any way to compensate for this?

**Comment by u01jmg3** [comment]
Let me have a look and get back to you

**Comment by cbcsouthlake** [comment]
Thanks!  I'll contact the vendor to see if they can send all the DateTimes in a single timezone.

**Comment by u01jmg3** [comment]
If you pull in the latest `dev-master` changes and set `defaultTimeZone` to `America/Chicago`, your 14 exdates should work as expected.

**Comment by cbcsouthlake** [comment]
Thanks!
dev-master:
DOES NOT filter out the exdates when defaultTimeZone is set to America/Chicago
DOES filter out the exdates when defaultTimeZone is set to UTC

**Comment by u01jmg3** [comment]
Second attempt - it was counter-intuitive

**Comment by cbcsouthlake** [comment]
That did it.  Thanks for the quick action.

**Comment by ace-wolf** [comment]
I have a similar problem, I made a Test event in google calendar and removed one event but it still shows up in the list.

![59c270be80add](https://user-images.githubusercontent.com/5586490/30646975-b2d78dbe-9e1a-11e7-93d4-3a7db1cee37c.jpg)

![59c270cc61501](https://user-images.githubusercontent.com/5586490/30646982-b98c1abc-9e1a-11e7-87e4-04558964f5df.jpg)

![59c2719151bb6](https://user-images.githubusercontent.com/5586490/30647137-22bad37a-9e1b-11e7-8c1e-b7d2b13108d6.jpg)

**Comment by ace-wolf** [comment]
Version from Sep 8 works for me tho

**Comment by u01jmg3** [comment]
@ace-wolf: can you provide the offending iCal?

**Comment by u01jmg3** [comment]
@cbcsouthlake, @ace-wolf: the introduction of [Carbon](carbon.nesbot.com/docs/) should fix all issues. Let me know.
