### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php' 

### ISSUE THREAD

**Issue by cleptric** [u01jmg3/ics-parser#162]
- ICS Parser Version: `2.1.0`

With version 2.1.0, Inside the `ICal.php` file the following line was added:

`require '../vendor/autoload.php';`

Was this done by accident?

**Comment by u01jmg3** [comment]
It was added in order to use Carbon.

**Comment by cleptric** [comment]
Normally it is sufficient to just require carbon inside the `composer.json`. (The one of `ics-parser)`
As we use the ics-parser itself as a composer package, it is installed into the `vendor` directory and composer should take care of loading Carbon on its own.

**Comment by u01jmg3** [comment]
Shall fix and re-release - thanks for the heads up. We shall go with accidental 😃
