### ISSUE TITLE
Time zone issue - Cannot get UTC

### ISSUE THREAD

**Issue by gavinr** [u01jmg3/ics-parser#166]
- PHP Version: `7.0.22`
- PHP date.timezone: `UTC`
- ICS Parser Version: `2.1.1`
- Linux

### Description of the Issue:

I think we are parsing iCal files that have time zones incorrectly. A typical file will look like this for me in the ICS:

```
BEGIN:VEVENT
DTSTART;TZID=America/New_York:20171107T120000
DTEND;TZID=America/New_York:20171107T130000
RRULE:FREQ=WEEKLY;UNTIL=20190102T045959Z;INTERVAL=2;BYDAY=TU
EXDATE;TZID=America/New_York:20171219T120000
DTSTAMP:20171119T222026Z
UID:asdf@google.com
CREATED:20171109T201238Z
DESCRIPTION:test
LAST-MODIFIED:20171109T201745Z
LOCATION:asdf
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:asdf
TRANSP:OPAQUE
END:VEVENT
```

The event is scheduled for 12:00 in the `America/New_York` time zone. If I call `$ical->iCalDateToDateTime($event->dtstart_array[3]);` I get back 12:00 UTC - that is incorrect.

### Steps to Reproduce:

1. ICS file with the above code block.
2.
```php
$events = $ical->eventsFromInterval('1 weeks');
foreach ($events as $event) {
    $ical->iCalDateToDateTime($event->dtstart_array[3]);
}

```
3. will give back a result for events that looks like:

```
(
    [date] => 2017-11-21 12:00:00.000000
    [timezone_type] => 3
    [timezone] => UTC
)
```
... but should be:
```
(
    [date] => 2017-11-21 17:00:00.000000
    [timezone_type] => 3
    [timezone] => UTC
)
```

**Comment by grizzly** [comment]
same here, any news?

**Comment by u01jmg3** [comment]
I have to admit this dropped off my radar - will make it a priority this weekend.

**Comment by u01jmg3** [comment]
You may not have spotted [`$forceTimeZone`](https://github.com/u01jmg3/ics-parser/blob/master/examples/index.php#L23) in the example?

Try:

```php
$events = $ical->eventsFromInterval('1 weeks');
foreach ($events as $event) {
    $ical->iCalDateToDateTime($event->dtstart_array[3], $forceTimeZone = true);
}
```

**Comment by u01jmg3** [comment]
Closing this issue due to a lack of activity. Happy to re-open if it is still a problem.

**Comment by murraycollingwood** [comment]
Okay - I'm having a problem.  Can we re-open please?

I'm loading the ICS
BEGIN:VEVENT
TRANSP:OPAQUE
DTSTART;TZID=Pacific\/Auckland:20191015T120000
DTEND;TZID=Pacific\/Auckland:20191015T125000
CREATED:20190101T000000Z
UID:E943400B00B5F7-THAZT-05FA
SEQUENCE:737329
SUMMARY:Sample ics
LOCATION:Localhost
DESCRIPTION:Sample
END:VEVENT

I'm trying to get this to a local unix timestamp: I have included the important lines of code and the relative values at each stage:

// event->dtstart_array[3] = TZID=Pacific/Auckland:20191015T120000
$dtstart = $ical->iCalDateToDateTime($event->dtstart_array[3], true);
// iCalDateToDateTime dtstart = 2019-10-15 12:00:00
$timestart = $dtstart->getTimestamp();
// getTimestamp timestart = 1571094000
strftime timestart = 2019-10-15 09:00:00

In the iCalDateToDateTime() I initially had false for the second parameter, I tried changing it to true, but it makes no difference to this result.

Maybe I'm doing something dumb, but I just can't see it.

TIA

**Comment by u01jmg3** [comment]
@murraycollingwood: please open a **new** issue filling in the issue template so I can properly assess the problem.
