### ISSUE TITLE
How to use example?

### ISSUE THREAD

**Issue by bulletxt** [u01jmg3/ics-parser#168]
Hi, sorry if writing here but I'm new to this and I'm not sure where to ask support.

I downloaded a copy of your repository,  doing from cli  "php examples/index.php" will just give an error saying it can't find  "require_once '../vendor/autoload.php';"  

How can I use this ical parser? Thanks a lot!

**Comment by bulletxt** [comment]
Hi, I was able to get this working... now I'll start digging more into this :) If I need help where can I ask?

**Comment by bulletxt** [comment]
I'm unable to parse this ics , this ics can be imported in any other software without issues.  Any suggestions ? 

Thanks
[TEST2-2017-12-14-172749.ics.txt](https://github.com/u01jmg3/ics-parser/files/1560016/TEST2-2017-12-14-172749.ics.txt)

**Comment by bulletxt** [comment]
I'm sorry, after struggling a bit I finally found my path.... it seems to be working! I also see you correctly handled multiple attendees... great!

**Comment by u01jmg3** [comment]
Glad you got things working. Closing for now.
