### ISSUE TITLE
Importing multiple ICS

### ISSUE THREAD

**Issue by searl08** [u01jmg3/ics-parser#175]
Hi,

Great product.
I am importing 33 ICAL's from VRBO and imports intermittently fail on different calendars.

My Code:
```
foreach($ical_props_arr as $row) {	
	$property_title=$row['title'];	
	$import_url=$row['ical_import_url'];
	try {						
		$ical = new ICal($import_url, array(
			'defaultSpan'           => 2,     // Default value
			'defaultTimeZone'       => 'UTC',
			'defaultWeekStart'      => 'MO',  // Default value
			'disableCharacterReplacement' => false, // Default value
			'skipRecurrence'              => false, // Default value
			'useTimeZoneWithRRules'       => false, // Default value
		));
	} catch (\Exception $e) {		
		$error.='An Error Occurred importing: '.$import_url."\n";		
		$error.=$property_title." Import ICAL URL, appears to be Bad!!\n\n";		
	}
}
```
All URL's are http:// and confirmed good. Is there possibly a timeout issue here?

Any help would be appreciated.
Thanks

**Comment by u01jmg3** [comment]
- Glad this tool is useful to you
- Without having access to the 33 iCal feeds it is difficult for me to diagnose.
- Have you tried extending PHP's maximum execution time from its default of 30 seconds?

```php
ini_set('max_execution_time', 300); // 300 seconds = 5 minutes
```

**Comment by searl08** [comment]
Hi Jonathan,

Here are the URL's:

http://admin.vrbo.com/icalendar/fb849531f32c4f089de5eab8f753fd7b.ics
http://admin.vrbo.com/icalendar/00e8c2da2c554cc3a663b95d189b76cd.ics
http://admin.vrbo.com/icalendar/cf8fe67f8a8a47c89a5c22818bd94454.ics
http://admin.vrbo.com/icalendar/68ddf234930046ed91e622b7dd30d73d.ics
http://admin.vrbo.com/icalendar/7cfad16dd61f42d4b66bfc75ad956076.ics
http://admin.vrbo.com/icalendar/8a9dff12fed34b119861a7662e9ab9b5.ics
http://admin.vrbo.com/icalendar/639b89598e034ca795c08d9c96aa6145.ics
http://admin.vrbo.com/icalendar/6ede8243c9b04c1a96e0b8fc53c45b81.ics
http://admin.vrbo.com/icalendar/4b6575ac2f5846c5bab17237acebaf50.ics
http://admin.vrbo.com/icalendar/aa8aa39d32b043a4819d1aeff3452d38.ics
http://admin.vrbo.com/icalendar/a2a34f60a1b24a71ba2fb74bd141f71e.ics
http://admin.vrbo.com/icalendar/b3746c1cef5b4cce83324aab23ec1ae3.ics
http://admin.vrbo.com/icalendar/bcd105978b494273a8f762d59dad985d.ics
http://admin.vrbo.com/icalendar/1387262ec7f248b09162ee38af8a3780.ics
http://admin.vrbo.com/icalendar/c66d55b097fd4538b2226b31a5860c4b.ics
http://admin.vrbo.com/icalendar/db2c30b907c84570b525282c74d226e4.ics
http://admin.vrbo.com/icalendar/94673b5a8ce54c41a24b4af194f831a6.ics
http://admin.vrbo.com/icalendar/94673b5a8ce54c41a24b4af194f831a6.ics
http://admin.vrbo.com/icalendar/9eb0f3e323ba49c9825c5c143af0ae90.ics
http://admin.vrbo.com/icalendar/c58a8a6d5a9a44818e286eef8b0dd39c.ics
http://admin.vrbo.com/icalendar/733a47707d974171827e3d328ca0ab7b.ics
http://admin.vrbo.com/icalendar/bac3c952d3a943819a8285fc3b9f9110.ics
http://admin.vrbo.com/icalendar/6425b0b23de14c07a315844ddbafa066.ics
http://admin.vrbo.com/icalendar/a60effecfa4844b78cc4b02c065d2ac8.ics
http://admin.vrbo.com/icalendar/0d54dc53a9034ad5b4ba068aafc1d896.ics
http://admin.vrbo.com/icalendar/705e996a7a244706b926928afa6583c5.ics
http://admin.vrbo.com/icalendar/4a3352c657cd4c058415f9cf54991964.ics
http://admin.vrbo.com/icalendar/bd095815f7904e27b1eb8ba5604319ca.ics
http://admin.vrbo.com/icalendar/aa62eac1a93f4e85a80d0474b39461c9.ics
http://admin.vrbo.com/icalendar/0741ac041c6c40d68146c501aad5c69f.ics
http://admin.vrbo.com/icalendar/d78b94d2046440f2ad65b6f1311b03f5.ics
http://admin.vrbo.com/icalendar/521af3b582ea4e4e85bc0534c1690d52.ics
http://admin.vrbo.com/icalendar/7e66fb0cee9b49d086f7a7fed4422af7.ics
http://admin.vrbo.com/icalendar/6fdcb4a564074a26bfd35d06f56390e5.ics

As you can see from my code, the URL's are stored in the array $ical_props_arr.

As I said, when looping this array, I get intermittent failures on getting the URL.

I'm not sure if it is vrbo.com, not keeping up with the requests or something else.

Thanks

**Comment by u01jmg3** [comment]
Thanks - have you tried extending the `max_execution_time`?

**Comment by searl08** [comment]
Hi Jonathan,

 

The function script has ini_set('max_execution_time', 800);

 

Thanks

**Comment by searl08** [comment]
Hi Jonathan,

The function script has ini_set('max_execution_time', 800);

Thanks

**Comment by u01jmg3** [comment]
Does the exception you see give any clue?

**Comment by searl08** [comment]
Hi Jonathan,

The ics-parser exception is:

exception 'Exception' with message 'The file path or URL 'admin.vrbo.com/icalendar/…; does not exist. 

Thanks

**Comment by u01jmg3** [comment]
Loads for me in around 15-20 seconds. Worked 4 out of 5 attempts where 2 errored out with HTTP stream errors.

Could the VBRO server be limiting the number of simultaneous requests? Or struggling to meet your demand?

You might have to build some logic into your loop which catches and retries a failed attempt and possibly delays between each request. You might then find things work more often. Either that or download the 33 iCal files locally with a cron before running ICS Parser.

Unless there is a particular bottleneck with ICS Parser I can't really recommend anything further.

**Comment by searl08** [comment]
Hi Jonathan,

I have a feeling it is the VRBO Server that isn't keeping up.
Does ics-parser use PHP curl_multi_init for processing of multiple cURL handles asynchronously. 
I already tried a the PHP copy method  for all the URL's, to the the my server, but ran into the same problem.
As far as the catch on failure with a delay, do I need to destroy and re-insantiate the ics-parser object or is there a way to re-trigger the original call after I add a delay?

Thanks for your time

**Comment by u01jmg3** [comment]
[`curl_multi_init()`](https://secure.php.net/manual/en/function.curl-multi-init.php) sounds like a good idea but it is not currently used within ICS Parser (more than happy to look over a PR should you want to submit one).

No need to destroy just instantiate a new ICal object each time keeping track of the previous should you require it at a later stage.

Would recommend using [Laravel collections](https://github.com/tightenco/collect) should you wish to deal with multi-dimensional arrays (instead work with collections).

**Comment by searl08** [comment]
Hi Jonathan,

Again, Thanks for your time.
