### ISSUE TITLE
Past events returned by eventsFromRange('now')

### ISSUE THREAD

**Issue by petermillgram** [u01jmg3/ics-parser#176]
It looks like `eventsFromRange()` uses `dtstart_array[2]` to compare dates. But as those values are produced by `iCalDateToUnixTimestamp()` called without its optional arguments, the comparison does not take time offsets into account. The result of this is that some of the events returned by `eventsFromRange('now')` can be in the past.

Is it the intended behavior? If so, is there a way to obtain only the future events from a calendar?

**Comment by u01jmg3** [comment]
> _The result of this is that some of the events returned by `eventsFromRange('now')` can be in the past._
> 
> _Is it the intended behaviour?_

Nope, won't be intended. Can you provide the offending iCal?

Happy to take a look at a PR if you have found a workaround.

**Comment by petermillgram** [comment]
> Can you provide the offending iCal?

    BEGIN:VCALENDAR
    VERSION:2.0
    BEGIN:VEVENT
    UID:d3b07384d113edec49eaa6238ad5ff00
    DTSTART;TZID=Europe/Rome:20180404T010000
    DTEND;TZID=Europe/Rome:20180404T020000
    SUMMARY:Test Event
    END:VEVENT
    END:VCALENDAR

It is now 3:00 AM in Rome, and I get this event when I call `eventsFromRange('now')`.
