### ISSUE TITLE
Undefined Offset 2 in sortEventsWithOrder

### ISSUE THREAD

**Issue by dasgarner** [u01jmg3/ics-parser#179]
In the below commit `$this->cal['VEVENT'] = $events;` has been placed inside an IF statement, which means the modified events array isn't stored at the end of process event.

`sortEventsWithOrder` then uses `dtstart_array[2]` which isn't set anymore, causing undefined index exception.

This commit introduced the issue:
https://github.com/u01jmg3/ics-parser/commit/72d3d0c82df6522e75e5a16ee7a51a64a135e52a#diff-50681920b8994c51dcfbb9a44850348f

Putting `$this->cal['VEVENT'] = $events;` back outside the IF statement fixes it.

**Comment by u01jmg3** [comment]
Thanks for reporting - checkout `v2.1.5`

**Comment by dasgarner** [comment]
No problem - thanks for the fast turnaround!
