### ISSUE TITLE
Windows zone names not supported?

### ISSUE THREAD

**Issue by marcelstoer** [u01jmg3/ics-parser#186]
- PHP Version: `7.1.16`
- PHP date.timezone: `UTC`
- ICS Parser Version: `2.1.4`
- Mac

### Description of the Issue:
Are Windows zone names not supported? This seems related to what @jasonheffner reported in #178.

I have an MS Exchange calendar that declares a custom timezone like so:

```
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
...
```

However, all timestamps referencing this TZID are treated as UTC as it's neither a valid IANA id nor a valid CLDR id.

### Steps to Reproduce:

```php
<?php
date_default_timezone_set("UTC");

require_once "./vendor/autoload.php";

use ICal\ICal;

$calendarString = "BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Test event for ics-parser
DTSTART;TZID=W. Europe Standard Time:20180925T140000
DTEND;TZID=W. Europe Standard Time:20180925T150000
UID:an-extremely-long-Microsoft-UID
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20180926T061553Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:My Room (my address, my city, my phone)
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR";

$ical = new ICal(false, array(
    "defaultSpan"                 => 1,
    "defaultWeekStart"            => "MO",
    "disableCharacterReplacement" => true,
    "skipRecurrence"              => false,
    "useTimeZoneWithRRules"       => false,
));
$ical->initString($calendarString);

$event = $ical->events()[0];
// dtstart_array contains: timezone, timestamp as string, unix timestamp (epoch), timezone + timestamp
// -> force it to be UTC
$start = $ical->iCalDateToDateTime($event->dtstart_array[3], true, true);
$end = $ical->iCalDateToDateTime($event->dtend_array[3], true, true);
echo "DTSTART:" . $start->format("Ymd\THis\Z") . "\n";
echo "DTEND:" . $end->format("Ymd\THis\Z");
```

This produces
```
DTSTART:20180925T140000Z
DTEND:20180925T150000Z
```
which is currently 2h off ("W. Europe Standard Time" means CET with DST).

**Comment by u01jmg3** [comment]
Time zones are tricky and this library does its best to provide support. Open to suggestions on how to solve your case...

**Comment by marcelstoer** [comment]
Something similar to what you do in `isValidCldrTimeZoneId`? Or map a Windows zone id (it's always you, Windows...) to a CLDR/IANA id early in the parsing phase and keep the rest as is?
Source: https://support.microsoft.com/en-ca/help/973627/microsoft-time-zone-index-values and http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml of course

**Comment by u01jmg3** [comment]
I can take a look at some point but I have little time to devote to fixing nuisance issues such as this unfortunately. 😞

**Comment by marcelstoer** [comment]
I don't take personal offence but don't you think calling "(partial) lack of support for MS Exchange" a "nuisance issue" is a bit...I don't know..._disappointing_ if you're developing an icalendar lib? I'm in the same boat though wrt having little time; too many open-source projects at hand.

Never mind, I already accepted that we'll have to fix this ourselves.

**Comment by u01jmg3** [comment]
I shall do my best. I actually meant to type 'nuance issue'.

**Comment by jasonheffner** [comment]
I originally worked around the issue and replaced the TZ name before sending it to the parser since I knew what the mappings were for all our ics files. It was a simple and quick workaround for the short term. You could also add the additional zone mappings to the code now that the mapping capability is written in.

**Comment by marcelstoer** [comment]
The most non-invasive would be for the parser to do the replacement while processing TZIDs. Otherwise, I guess, one would need to change all the places where "isValidCldrTimeZoneId or isValidIanaTimeZoneId" is evaluated and add a `isValidWindowsTimeZoneId` function.
