### ISSUE TITLE
Feature Request: Support calendars with basic auth

### ISSUE THREAD

**Issue by samuelstein** [u01jmg3/ics-parser#195]
I have a .ics calendar which is protected with basic auth. 
That's not supported from the great parser right now. 
Would be nice if the lib would support HTTP Basic auth.

**Comment by u01jmg3** [comment]
How does [this branch](https://github.com/u01jmg3/ics-parser/compare/feature-http-basic-auth) suit?

(Note to self, the documentation needs to be updated!)

**Comment by samuelstein** [comment]
hi,
thanks. works like charme (with nextcloud calendar app).
