### ISSUE TITLE
Wrong recurrence handling

### ISSUE THREAD

**Issue by pikim** [u01jmg3/ics-parser#196]
- PHP Version: `7.2.10`
- PHP Default timezone: `UTC`
  - PHP date.timezone: `no value`
- ICS Parser Version: `2.1.7`
- Linux

### Description of the Issue:

When I load the attached file, ics-parser gives me 6 events:
- dtstart: "20191105T190000"
  "rrule": "FREQ=DAILY;UNTIL=20191111T180000Z"
- dtstart: "20191106T190000"
  "rrule": "FREQ=DAILY;UNTIL=20191111T180000Z"
- dtstart: "20191107T190000"
  "rrule": "FREQ=DAILY;UNTIL=20191111T180000Z"
- dtstart: "20191108T190000"
  "rrule": "FREQ=DAILY;UNTIL=20191111T180000Z"
- dtstart: "20191109T170000"
  "recurrence_id": "20191109T190000"
- dtstart: "20191110T180000"
  "recurrence_id": "20191110T190000"

When I parse this I get the event 2 times on the 6th, 3 times on the 7th, 4 times on the 8th and so on.

### Steps to Reproduce:

Rename [test.txt](https://github.com/u01jmg3/ics-parser/files/2640806/test.txt) to *.ics and load it with:

```php
$ical_file = "path/to/file";
$ical = new ICal(
    $ical_file,
    array(
        'defaultSpan'                 => 2,     // Default value
        'defaultTimeZone'             => 'UTC',
        'defaultWeekStart'            => 'MO',  // Default value
        'disableCharacterReplacement' => false, // Default value
        'filterDaysAfter'             => null,  // Default value
        'filterDaysBefore'            => null,  // Default value
        'replaceWindowsTimeZoneIds'   => false, // Default value
        'skipRecurrence'              => false, // Default value
        'useTimeZoneWithRRules'       => false, // Default value
    )
);
$events = $ical->sortEventsWithOrder($ical->events());
```

**Comment by pikim** [comment]
> Can you confirm what is the expected output versus the actual? i.e. spell out what is wrong with what you are seeing

As I wrote above I'm getting one event starting at 2019110**5**T190000 and ending at 20191111T180000Z, another event starting at 2019110**6**T190000 and ending at the 20191111T180000Z, another event starting at 2019110**7**T190000 and ending at the 20191111T180000Z, and so on. 

That means I have the event once on the 5th, twice on the 6th, three times on the 7th, five times on the 8th, and so on.

**Comment by hubermat** [comment]
Basically everything is okay, the ics-parser reads the file correctly and returns the right events in $events. See the unit test that I created for this case.

The problem occurs, if you then try to re-parse the generated events _again_, as each generated event is marked as belonging to a recurrence, but is then interpreted as a recurrence of its own. But I currently don't see why you would re-parse the events again, if you already have the single events.

**Comment by pikim** [comment]
But I'm pretty sure that I parse the file only once. Please see the original issue description.

**Comment by hubermat** [comment]
You wrote: "When I load the attached file, ics-parser gives me 6 events: ..."
Those are the correctly parsed event. All fine.

Then you wrote: "When I parse this I get the event 2 times on the 6th, 3 times on the 7th, 4 times on the 8th and so on." 
=> there is no need to "parse this"! The 6 events you got from the ics-parser in the first place is already all you need.

**Comment by pikim** [comment]
Hello,

I didn't work on this any more, but now I'm back on this topic.

I think my last posts were very unclear. What I wanted to say: in my opinion the parser should either return one event for each day or one single event with an rrule.

Currently it returns an event for each day and each of those events has an rrule. If one processes those events and considers the rrules, one gets the event multiple times.

**Comment by pikim** [comment]
Hello,

I didn't work on this topic for a while, but now I'm back.

I think my former posts were unclear. What I wanted to say that the parser should either return an event for each day without rrule or one single event for all days with rrule.

Currently it returns one event for each day and each of those events has an rrule. If one considers the rrule it leads to multiple events on the same day, e.g. 2 events on 2nd day, 3events on 3rd day, ...

**Comment by sherpadawan** [comment]
I use ical-expander with fullcalendar in javascript.
Not php anyway.
