### ISSUE TITLE
Question: how to get a single event as an iCal object?

### ISSUE THREAD

**Issue by samuelstein** [u01jmg3/ics-parser#199]
Is it possible to get a single event as an iCal object?

**Comment by u01jmg3** [comment]
The parser returns events as an associated array of `ICal\Event` objects. Stating the index you want from the array or iterating through the results would be how you would read what the parser has found.

Without more detail about what you are trying to achieve, I can't really suggest anything more.

**Comment by samuelstein** [comment]
Thanks. Sorry for not clarifying. My intend is to offer a ical download link. Should i still go this way?
