### ISSUE TITLE
isFileOrUrl returns warning if filename is too long

### ISSUE THREAD

**Issue by caco3** [u01jmg3/ics-parser#200]
I got the following error:

```
Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096): BEGIN:VCALENDAR VERSION:2.0 PRODID:-//Nextcloud calendar v1.6.4 CALSCALE:GREGORIAN BEGIN:VTIMEZONE TZID:Europe/Zurich X-LIC-LOCATION:Europe/Zurich BEGIN:DAYLIGHT TZOFFSETFROM:+0100 TZOFFSETTO:+0200 TZNAME:CEST DTSTART:19700329T020000 RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU END:DAYLIGHT BEGIN:STANDARD TZOFFSETFROM:+0200 TZOFFSETTO:+0100 TZNAME:CET DTSTART:19701025T030000 RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU END:STANDARD END:VTIMEZONE BEGIN:VEVENT CREATED:20181202T235046 SUMMARY:*** LOCATION: STATUS:CONFIRMED TRANSP:OPAQUE DESCRIPTION:*** RRULE:FREQ=WEEKLY;UNTIL=20190703T215900Z;INTERVAL=2;WKST=MO;BYDAY=TU LAST-MODIFIED:20190115T194435Z DTSTAMP:20190115T194435Z SEQUENCE:2 CLASS:PUBLIC DTSTART;TZID=Europe/Zurich:20190115T194500 DTEND;TZID=Europe/Zurich:20190115T213000 UID:HB8RNNI9SJB5JIHD0FFSOG END:VEVENT BEGIN:VEVENT DTSTART;TZID=Europe/Zurich:20190129T194500 DESCRIPTION:*** /***/libs/ICal/ICal.php on line 2598
```

For some reasons this function processes the file CONTENT and not the FILENAME. I don't understand why, also I didn't touch the code at all. 

The solution simply is to suppresses the warning by appending an @ before `file_exists`:

```php    
protected function isFileOrUrl($filename)
{
    return (@file_exists($filename) || filter_var($filename, FILTER_VALIDATE_URL)) ?: false;
}
```

**Comment by u01jmg3** [comment]
Can you please fill in the issue template correctly? It provides me with vital information in order to properly review the problem you are facing.

Using `@` is not the correct solution in this instance or any other.

---

## Issue Template:

> :information_source:
> - Firstly, check you are using the latest version (`dev-master`) as the problem may already have been fixed.
> - It is **essential** to be provided with the offending iCal causing the parser to behave incorrectly.
>   - Best to upload the iCal file directly to this issue
> - [Create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
>   - Minimal - use as little code as possible that still produces the same problem
>   - Complete - provide all parts needed to reproduce the problem
>   - Verifiable - test the code you're about to provide to make sure it reproduces the problem

- PHP Version: `7.#.#`
- PHP date.timezone: `[Country]/[City]`
- ICS Parser Version: `2.#.#`
- Windows/Mac/Linux

### Description of the Issue:


### Steps to Reproduce:

1.
1.
1.

**Comment by u01jmg3** [comment]
Not enough info, closing but happy to re-open.
