### ISSUE TITLE
Warning: mb_strlen(): Unknown encoding "auto"

### ISSUE THREAD

**Issue by stijink** [u01jmg3/ics-parser#202]
- PHP Version: `7.3`
- ICS Parser Version: `2.1.8`
- Linux

### Description of the Issue:
Since updating to version 2.1.8 im getting the error message `Warning: mb_strlen(): Unknown encoding "auto"`. It was working fine in version 2.1.7.

Must be related to the commit https://github.com/u01jmg3/ics-parser/commit/db41e233f63e526acbe69261212eabf57008b4be

**Comment by u01jmg3** [comment]
Appreciate you logging this

Can you try the branch [`issue-202`](https://github.com/u01jmg3/ics-parser/compare/issue-202) and let me know if it fixes the problem?

**Comment by u01jmg3** [comment]
See [`v2.1.9`](https://github.com/u01jmg3/ics-parser/releases/tag/v2.1.9)

**Comment by boscho87** [comment]
thank you for your great work !

**Comment by stijink** [comment]
@u01jmg3 Thank you :-)

**Comment by stijink** [comment]
@u01jmg3 Now, with version 2.1.9 it is working as expected.
