### ISSUE TITLE
Feature: add custom header as option

### ISSUE THREAD

**Issue by finchen** [u01jmg3/ics-parser#205]
### Description of the Issue:

It would be good to be able to set the headers.
Site like Facebook does not let read the iCalendar directly (they return an `unknown browser` error)

### Something like that is working

```php
$options = array(
  'http' => array(
    'header' => "User-Agent: Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/44.0.4 Mobile/7B334b Safari/531.21.102011-10-16 20:23:10\r\n" // i.e. An iPad
  )
);

$context = stream_context_create($options);
```

**Comment by u01jmg3** [comment]
Let me know what you think of 205afb3 in branch `issue-205`

**Comment by finchen** [comment]
It's looking good. I will try it soon. Thanks

**Comment by u01jmg3** [comment]
Any luck trying it out? Would like to get this merged

**Comment by finchen** [comment]
sorry it took so long. I struggled with composer.

There is a syntax error. I fix it with:
```
array_push($options['http']['header'], "User-Agent: {$this->httpUserAgent}");
```

and then it works as expected! Thanks
