### ISSUE TITLE
Problem with iCal calendar that shows times wrong

### ISSUE THREAD

**Issue by machfr** [u01jmg3/ics-parser#208]
I am having an issue where I have this Ical (Icloud): https://p59-calendars.icloud.com/published/2/NTU4MDkwODI4NTU4MDkwOFQqNMVtnNFS5S6Msuf6RmTzb4vQHQEI-ztPF8YDoroopzBpaSwui-TIyZju7LexUnrUXMiTuteNl2iNgttSYQ8

and on the 12th (today) I have en even running from `09:30` - `10:15` but when it comes out through the parser the `dtstart_tz` is set to `10:30` and `dtend_tz` to `11:15` which is `1` hour wrong.

I have tried to do the same with other calendars created in google, outlook and other places and they all get `dtstart_tz` and `dtend_tz` set correctly

the config is set as the follow:

```php
$ical = new ICal($calendar_url, array(
    'defaultSpan'                 => 2,
    'defaultWeekStart'            => 'MO',
    'disableCharacterReplacement' => false,
    'filterDaysAfter'             => null,
    'filterDaysBefore'            => 1,
    'replaceWindowsTimeZoneIds'   => false,
    'useTimeZoneWithRRules'       => true,
));
```

someone able to maybe give me a hint on what is going wrong?

**Comment by machfr** [comment]
![Screenshot 2019-03-12 at 12 58 56](https://user-images.githubusercontent.com/48055366/54198389-a42aea00-44c6-11e9-9ff3-02d98c7b01a7.png)

Could maybe add that this shows that dtstart_array has the correct time where dtstart_tz dosen't, just to show you what the output from the parser gives as it might make it easier to give feedback on it.

**Comment by u01jmg3** [comment]
Will try and find time this weekend to take a look but please proceed with your own investigation meantime. I don't get a lot of time to work on issues these days.

**Comment by machfr** [comment]
Ok, so I have found out that it goes wrong when you do this around line 1048: 
$dateTime = new \DateTime($dateArray[1], new \DateTimeZone(self::TIME_ZONE_UTC));
$dateTime->setTimezone(new \DateTimeZone($this->calendarTimeZone()));

Where you take the time that stands as 9:30 and say it is utc aka. uk time then after you set the timezone to europe/copenhagen which makes the time go one hour head. compared to what it should
