### ISSUE TITLE
Question about filterDaysBefore/filterDaysAfter options

### ISSUE THREAD

**Issue by diff-dennis** [u01jmg3/ics-parser#215]
Hi, I have a question about the usage of this package:

Is there a way to use the `filterDaysBefore` and `filterDaysAfter` options with a date other than `now`? Let's say I have a large iCal file and I want to parse only one day of the next week, is it possible to specify this day and skip the days before and after that?

Thank you!

**Comment by u01jmg3** [comment]
It looks like @marcelstoer implemented this feature [allowing only `now`](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L471-L472).

I don't see why this couldn't be opened up to allow a given day. Happy to accept a PR.
