### ISSUE TITLE
Possible filter days before and after bug

### ISSUE THREAD

**Issue by roelVerdonschot** [u01jmg3/ics-parser#216]
When using the before and after filter events inside the range were removed, I had to update 1 line and add an extra check (parentheses) to make it work.

I changed this line in `removeLastEventIfOutsideWindowAndNonRecurring()`

- `if (!isset($lastEvent['RRULE']) || $lastEvent['RRULE'] === '' && $this->doesEventStartOutsideWindow($lastEvent)) {`

to

- `if ((!isset($lastEvent['RRULE']) || $lastEvent['RRULE'] === '') && $this->doesEventStartOutsideWindow($lastEvent)) {`

and had to add this if to the `$events` `foreach` in `reduceEventsToMinMaxRange()`

```php
if ($anEvent === null) {
    unset($events[$key]);
    continue;
}
```

I'm using `v2.1.11`

**Comment by u01jmg3** [comment]
Thanks for letting know.

What iCal broke the parser and required the changes you mentioned above?

Can you send in a PR with your changes?

Thanks

**Comment by roelVerdonschot** [comment]
I've send in a PR but I cannot send the iCal because of company policies/privacy reasons.
