### ISSUE TITLE
Does not work with PHP 5.3.9

### ISSUE THREAD

**Issue by Ben-Ho** [u01jmg3/ics-parser#223]
- PHP Version: `5.3.13`
- PHP date.timezone: `...`
- ICS Parser Version: `2.1.11`
- Linux

### Description of the Issue:
php syntax problems

### Steps to Reproduce:

1. initialise ical object with php 5.3

**Comment by u01jmg3** [comment]
- What syntax errors do you get?
- As PHP `5.3` was end of life on 14 Aug 2014 I think I may bump up the minimum requirement to PHP `5.6.40`.

**Comment by Ben-Ho** [comment]
Sorry for my late response. The first error was "short array syntax". I didn't investigated any further as I found a workaround by generating a csv on my local machine using this instead of the ics-file on prod-server...
https://www.php.net/manual/en/migration54.new-features.php
