### ISSUE TITLE
Every week with interval 2 on monday don't work correct

### ISSUE THREAD

**Issue by arwinvdv** [u01jmg3/ics-parser#224]
### Description of the Issue:

With this weekly event on monday with an interval of 2, the parser create the following events: 1 july, 8 july, 15 july, 29 july. So the 8 july is not correct. I will create a pull request.

### Steps to Reproduce:

1. Create an ics with this event:

```
BEGIN:VEVENT
CREATED:20190630T065550Z
DTEND;TZID=Europe/Amsterdam:20190701T080000
DTSTAMP:20190630T143919Z
DTSTART;TZID=Europe/Amsterdam:20190701T070000
LAST-MODIFIED:20190630T143919Z
RRULE:FREQ=WEEKLY;INTERVAL=2
SEQUENCE:0
SUMMARY:Test event
UID:D86AB593-29D0-4523-A3B9-680BE46C729E
URL;VALUE=URI:
END:VEVENT
```

- https://www.ligon.nl/projects/testical.ics

1. Parse the recurring event and the dates above are generated.

**Comment by u01jmg3** [comment]
Fixed by 3bbd832
