### ISSUE TITLE
Wrong recurrence handling #196

### ISSUE THREAD

**Issue by pikim** [u01jmg3/ics-parser#231]
Hello,

I didn't work on this topic for a while, but now I'm back. This issue is the follow-up to #196 as this was closed and I cannot reopen it.

I think my former posts were unclear. What I wanted to say is that, in my opinion, the parser should either return an event for each day without rrule or one single event for all days with an rrule.

Currently it returns one event for each day and each of those events has an rrule field. If one considers the rrule it leads to multiple events on the same day, e.g. 2 events on 2nd day, 3 events on 3rd day and so on.

**Comment by u01jmg3** [comment]
> _the parser should either return an event for each day without rrule or one single event for all days with an rrule_

I have no plans to change how the parser returns recurrence events.

> _it leads to multiple events on the same day, e.g. 2 events on 2nd day, 3 events on 3rd day and so on_

If the parser is incorrectly parsing an ICS file I would be happy to take a look.

**Comment by pikim** [comment]
I don't know whether it's incorrect, but at least it's very unexpected.

Take the ics file from the old issue as an example:
Mainly there is one event in it with a daily RRULE. So this is just one event, repeated every day for one week, starting on the 5. November, ending on the 11. November.

But the ics-parser will return 7 events:
the first one starting on the 5. with a daily rrule until the 11.
the second one starting on the 6. with a daily rrule until the 11.
the third one starting on the 7. with a daily rrule until the 11.
the fourth one starting on the 8. with a daily rrule until the 11.
the fifth one starting on the 9. with a daily rrule until the 11.
and so on.

And if someone parses those events and their rrules to fill a calendar or anything like this, it will result in multiple identical events from the second day on (2 events on 2nd day, 3 events on 3rd day, 4 events on 4th day, ...)

**Comment by u01jmg3** [comment]
Happy to review a draft PR with a change to the current behaviour if you want to pull something together.

**Comment by alexander-47u** [comment]
For me it is also messed up with weekly recurrence. I enter recurrence, every other week in September, 8, 22th etc. But somehow it parses the ics file and enters the 8th, 15th and the 29th.

https://calendar.google.com/calendar/ical/h04e326l112aeu1oik959ovbkg%40group.calendar.google.com/private-624e89a537d5a9a9f1609830933a8814/basic.ics

This is the file that is failing on me.

**Comment by u01jmg3** [comment]
@alexander-47u: if you are experiencing an issue with the parser please kindly raise a new issue filling in the template which provides me with the necessary information to investigate your problem further.

**Comment by u01jmg3** [comment]
I'm happy with the current implementation so closing for now
