### ISSUE TITLE
Support 'RRULE:FREQ=MONTHLY;BYDAY=1SU,3SU;UNTIL=xxxxx

### ISSUE THREAD

**Issue by scottatmonk** [u01jmg3/ics-parser#235]
PHP Version: 7.3.1
    ICS Parser Version: 2.1.13
    Mac

Description of the Issue:

RRULE:FREQ=MONTHLY;BYDAY=1SU,3SU;UNTIL=xxxxx is leaving off second day ie. ,3SU

**Comment by s0600204** [comment]
(Duplicate of #15, is it not?)

**Comment by u01jmg3** [comment]
Closing in favour of #156 

@scottatmonk: happy to accept a PR should you wish to have this functionality
