### ISSUE TITLE
No Events without RRule

### ISSUE THREAD

**Issue by fogx** [u01jmg3/ics-parser#237]
Hi, im trying to use the ICS-Parser to parse a google calendar. It works fine with reocurring events, but i just noticed that no event without a RRule is shown at all. 
Im using the example script with these ical settings:
```
try {
    $ical = new ICal('ICal.ics', array(
        'defaultSpan'                 => 1,     // Default value
        'defaultTimeZone'             => 'UTC',
        'defaultWeekStart'            => 'MO',  // Default value
        'disableCharacterReplacement' => false, // Default value
        'filterDaysAfter'             => 1,  // Default value
        'filterDaysBefore'            => 1,  // Default value
	'shouldFilterByWindow'        => true, //activates filterDaysBefore/After
        'replaceWindowsTimeZoneIds'   => false, // Default value
        'skipRecurrence'              => false, // Default value
        'useTimeZoneWithRRules'       => false, // Default value
    ));
```
and
`init url(google cal private url, $username = null, $password = null, $userAgent = null)`

I attached the output of the google calendar (ABC no RRULE) and the ICS Parser script (no ABC event)

[google-calendar.txt](https://github.com/u01jmg3/ics-parser/files/3495930/google-calendar.txt)
[ics-parser.txt](https://github.com/u01jmg3/ics-parser/files/3495931/ics-parser.txt)

I can't find anything about having to enable non-reoccuring events. Am i doing something wrong or is this a bug?

**Comment by fogx** [comment]
adding a valid rrule entry such as `RRULE:FREQ=WEEKLY;BYDAY=WE` to the event will make it display properly again

**Comment by u01jmg3** [comment]
Trying this on the latest version of the parser and I see no issues:

![2019-08-18-17-27-localhost](https://user-images.githubusercontent.com/1266205/63227379-9f890100-c1dd-11e9-8d48-092cf27546bd.png)

**Comment by fogx** [comment]
yes it seems i did not update to the newest version! Although its strange, since it worked before and i didnt update.
Anyway, it works again now... thanks for your time!
