### ISSUE TITLE
Recurrence rule: last event missing

### ISSUE THREAD

**Issue by pikim** [u01jmg3/ics-parser#238]
- PHP Version: 7.2.10
- PHP Default timezone: UTC
    - PHP date.timezone: no value
- ICS Parser Version: 2.1.13
- Linux

### Description of the Issue:
The last event of a recurrence rule is missing. In the attached file is an recurring event with

```
RRULE:FREQ=DAILY;UNTIL=20191111T180000Z
DTSTART;TZID=Europe/Berlin:20191105T190000
DTEND;TZID=Europe/Berlin:20191105T220000
```

This should result in 7 events with the last one on November 11th. The parser returns 6 events with the last one on November 10th.

### Steps to Reproduce:
Rename [test.txt](https://github.com/u01jmg3/ics-parser/files/2640806/test.txt) to `*.ics` and load it. Dump the returned events.

**Comment by britweb-tim** [comment]
I'm seeing a similar issue here with an iCal feed.  The last event in this series on Sunday 1st September is missing.

```
DTSTART;TZID=Europe/London:20190818T103000
DTEND;TZID=Europe/London:20190818T111500
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20190902;BYDAY=SU

```

**Comment by u01jmg3** [comment]
@s0600204: looks like there is an issue with the code for computing `WEEKLY` `$matchingDays`.

- https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L1352

```php
foreach ($matchingDays as $day) {
    $clonedDateTime = clone $frequencyRecurringDateTime;

    var_dump($clonedDateTime->format('c'));
    // 2019-08-18T10:30:00+01:00

    $candidateDateTimes[] = $clonedDateTime->setISODate(
        $frequencyRecurringDateTime->format('Y'),
        $frequencyRecurringDateTime->format('W'),
        $day
    );

    var_dump(end($candidateDateTimes)->format('c'));
    // 2019-08-11T10:30:00+01:00
}
```

`$frequencyRecurringDateTime->format('W') + 1` fixes the issue but why would the week number be out by `1`?

**Comment by s0600204** [comment]
Hmm, yes, I see it.

It seems I need to rethink how to map different week starts onto a method (`setISODate()`) that expects weeks to start on a Monday. :thinking:

The week number is correct - it's `$day` that's potentially incorrect: in the above example it will be `0` (which within `setISODate()` equates to the last day of the week previous to the one identified by the passed week number).

I should have time to look into it this weekend.

**Comment by u01jmg3** [comment]
> _The week number is correct - it's `$day` that's potentially incorrect_

Almost!

> _I should have time to look into it this weekend._

Perfect

**Comment by pikim** [comment]
The original issue is not fixed, yet. Weekly rules may work now, but s0600204 didn't change anything in the code for daily rules.

**Comment by u01jmg3** [comment]
I see 7 events from your iCal:

![2019-09-02-12-46-localhost](https://user-images.githubusercontent.com/1266205/64112612-d6cfe400-cd7f-11e9-8afb-4486e1d26f24.png)

**Comment by pikim** [comment]
I only see 6 events.

My code
```
        // open and parse iCalendar files
        $ical = new ICal(
            "https://github.com/u01jmg3/ics-parser/files/2640806/test.txt",
            array(
                'defaultSpan'                 => 2,     // Default value
                'defaultTimeZone'             => 'UTC',
                'defaultWeekStart'            => 'MO',  // Default value
                'disableCharacterReplacement' => false, // Default value
                'filterDaysAfter'             => null,  // Default value
                'filterDaysBefore'            => null,  // Default value
                'replaceWindowsTimeZoneIds'   => false, // Default value
                'skipRecurrence'              => false, // Default value
                'useTimeZoneWithRRules'       => false, // Default value
            )
        );

        // get events sorted by date
        $events = $ical->sortEventsWithOrder($ical->events());
        dump($events);
```
gives me
![6events](https://user-images.githubusercontent.com/11775849/64115337-a2642400-cd8f-11e9-9ba5-c87e708466ec.png)

For details see: [6events.txt](https://github.com/u01jmg3/ics-parser/files/3566049/6events.txt)

**Comment by s0600204** [comment]
May we ask what version of the parser you're currently running?

**Comment by u01jmg3** [comment]
I am still getting **7** events as expected:

![2019-09-02-14-29-localhost](https://user-images.githubusercontent.com/1266205/64118794-477efc80-cd90-11e9-88e4-f4097b8057f4.png)

---

Your code is almost identical to the defaults so nothing obviously wrong there. To note `replaceWindowsTimeZoneIds` and `useTimeZoneWithRRules` options are now obsolete and can be removed.

**Comment by pikim** [comment]
> May we ask what version of the parser you're currently running?

I updated to v2.1.14 via Composer and replaced ICal.php manually with the one from https://github.com/u01jmg3/ics-parser/commit/e0e1b83acfd00fd17dbab0f871cc4f56c350fada just to create the results from my last post. I was on v2.1.13 before.

**Comment by u01jmg3** [comment]
To clarify, has [`dev-master`](https://getcomposer.org/doc/articles/aliases.md#branch-alias) (which is effectively what you are using) fixed your problem?

**Comment by pikim** [comment]
I took my base project (https://github.com/pikim/grav-plugin-events) updated the dependencies and replaced the ICal.php manually.

I didn't try it your way. I'll try to find out how I have to put the lines from your link into my project. I'm not too familiar with Composer, yet.

**Comment by s0600204** [comment]
When I try it locally, I too get **7** events.

----

I know nothing about - let alone ever used - [Grav CMS](http://getgrav.org/); but I thought I'd try setting up a basic install to see if perhaps there was some incompatibility with either **Grav** or @pikim's **events plugin** for it.

So, I acquired a copy of the current stable release of **Grav** (`v1.6.15`), along with a copy of the `master` branch of the **events plugin**, and installed them on an online webhost. I also manually replaced the `ICal.php` file within the plugin with the version from e0e1b83.

I had to make the following changes to `classes/iCalendarProcessor.php` of the *events plugin* to get it to parse the file...

```diff
@@ -159,11 +159,14 @@
         $location = $event->location;
         $description = $event->description;
         $last_modified = strtotime($event->last_modified);
-        $recurrence_id = strtotime($event->recurrence_id);
+        if (isset($event->recurrence_id)) {
+            $recurrence_id = strtotime($event->recurrence_id);
+        }
         $start = strtotime($event->dtstart);
         $end = strtotime($event->dtend);
 
         // split if element exists
+        $categories = array();
         if( isset($event->categories) ) {
             $categories = explode(',', $event->categories);
         }
```

...but made no other changes or altered any configuration from the defaults beyond providing the path to the remote file that I wished it to process ([the same one as in the original post](https://github.com/u01jmg3/ics-parser/files/2640806/test.txt)).

After selecting "Save" in the Admin layout, the events in the file were output across 7 files (one for each event): ![grav](https://user-images.githubusercontent.com/2053873/64219419-5d3e1000-cebd-11e9-8eb0-20ca9633ee05.png)

@pikim have you made any changes to your plugin that you haven't made public?

**Comment by u01jmg3** [comment]
@s0600204: thanks for checking things out further!

@pikim: closing this issue for now but happy to re-open if required

**Comment by pikim** [comment]
This is strange. I only get 6 events from the input file, never 7. May this be caused by any timezone setting in PHP or any other setting from my hosting provider?

My result from the latest Github code without any modifications looks like this:
![grafik](https://user-images.githubusercontent.com/11775849/66259364-771a8d80-e7b0-11e9-8b99-0828e730dbd8.png)
