### ISSUE TITLE
Question: Access ctag from ical

### ISSUE THREAD

**Issue by samuelstein** [u01jmg3/ics-parser#243]
Is there a possibility to access the **ctag** from the ical feed to determine if the calendar has changed?

**Comment by s0600204** [comment]
`ctag` is not a valid iCal component, property, or data value type, so no.

Whilst the parser can read calendar data from a myriad of sources (including URLs), it expects whatever it's passed to contain or point at calendar data directly, not to some API or object dealing with metadata.

**Comment by samuelstein** [comment]
okay, this i didn't knew. is there a other common way to detect changes from calendars via caldav?
