### ISSUE TITLE
RRULE:FREQ=WEEKLY - missing first event of the year

### ISSUE THREAD

**Issue by gavinr** [u01jmg3/ics-parser#251]
- PHP Version: `7.2.24`
- ICS Parser Version: `2.1.16`
- `Linux`

### Description of the Issue:
If you have an event that repeats weekly, and the original start date is on december 30, the first event of the new year (should be on jan 6) is missed. Example ICS: [example.zip](https://github.com/u01jmg3/ics-parser/files/4017981/example.zip).

![image](https://user-images.githubusercontent.com/209355/71704569-0bf24e80-2dd3-11ea-8594-440d37b86f7c.png)

### Steps to Reproduce:

1. Run against the attached ICS.

**Comment by u01jmg3** [comment]
A new release will be coming shortly but `dev-master` should fix your issue

**Comment by gavinr** [comment]
@u01jmg3 - great - thank you VERY much for looking into this and fixing it!

**Comment by u01jmg3** [comment]
Thanks goes to @s0600204
