### ISSUE TITLE
[Feature Request] Add "Accept-language" to the header options

### ISSUE THREAD

**Issue by Wilkware** [u01jmg3/ics-parser#253]
It is possible to add a option to pass the accepted language for the request? This would be nice!

Background:

The summary for private appointments will be always printed as "Privat Appointment", but if you pass in the header "Accept-language: de" then you will get "Privater Termin" (german) ;-)

Thanks Heiko

**Comment by u01jmg3** [comment]
Sure - feel free to send in a pull request.
