### ISSUE TITLE
Undefined offset: 2 in src/ICal/ICal.php on line 1692

### ISSUE THREAD

**Issue by room34** [u01jmg3/ics-parser#264]
With display_errors on, I have in a previous version run into an undefined offset error in the code that currently appears at line 1692 in src/ICal/ICal.php. Since the code has not been changed in this version, I assume the problem persists. I've previously resolved this by modifying that line with a conditional:

```php
<?php

if (isset($valuesList[$setPosition - 1])) {
    $filteredMatches[] = $valuesList[$setPosition - 1];
}
```

I just updated to version 2.1.18 and verified that this issue persists in the new version. The conditional resolves it.

**Comment by u01jmg3** [comment]
PR welcome :)
