### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by nekromoff** [u01jmg3/ics-parser#265]
- PHP Version: `7.4.6`
- PHP date.timezone: `Slovakia/Bratislava`
- ICS Parser Version: ` 2.1.16`
- Linux

### Description of the Issue:
Stack trace:
```
Trying to access array offset on value of type bool in ICal.php line 616
--
at HandleExceptions->handleError()in ICal.php line 616
at ICal->initLines()in ICal.php line 560
at ICal->initFile()in ICal.php line 588

```

### Steps to Reproduce:
I can not provide imported URL due to privacy reasons. I am able to test whatever, if you have suggestions.

**Comment by u01jmg3** [comment]
Have you tried the latest version (`2.1.19`)?

**Comment by nekromoff** [comment]
this disappeared after upgrading to v `2.6.19`, however #266 is new one
