### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in Event.php line 198

### ISSUE THREAD

**Issue by nekromoff** [u01jmg3/ics-parser#266]
After update from 2.6.16 to 2.6.19, issue #265 disappeared

- PHP Version: `7.4.6`
- PHP date.timezone: `Slovakia/Bratislava`
- ICS Parser Version: `2.6.19`
- LInux

### Description of the Issue:
`Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in Event.php line 198`

### Steps to Reproduce:
Importing private URL

**Comment by nekromoff** [comment]
Maybe related to emojis or HTML entities?

**Comment by u01jmg3** [comment]
Without ICS to test against I have no way of working out what the issue is

**Comment by nekromoff** [comment]
Any tips on how to debug this using break points (debug logs) in `Event.php`?

**Comment by nekromoff** [comment]
Maybe you will know more, I am doing `print_r($key)` in `__construct`:
```
MODIFIEDSEQUENCE_arraySEQUENCESTATUS_arraySTATUSSUMMARY_arraySUMMARYTRANSP_arrayTRANSPDTSTART_tzDTEND_tzDTSTART_arrayDTSTARTDTEND_arrayDTENDRRULE_arrayRRULEDTSTAMP_arrayDTSTAMPUID_arrayUIDCREATED_arrayCREATEDDESCRIPTION_arrayDESCRIPTIONLAST-MODIFIED_arrayLAST-MODIFIEDSEQUENCE_arraySEQUENCESTATUS_arraySTATUS 
```
(last STATUS is where it fails)

**Comment by u01jmg3** [comment]
I'm going to need some formatting of your output...

**Comment by u01jmg3** [comment]
The issue is related to the key part of the key/value pairs in your ICS

**Comment by nekromoff** [comment]
Yeah, multiple characters in multiple events such as emojis ⚔️🛡️  or non-UTF8 characters for accepted invitations from (I suspect) external systems such as:
```
SÃºÄasnÃ½  â akÃ© nÃ¡m
  beÅ¾ia v \n\nÃ¼   â akÃ½ nastavenÃ½
```

Usually in `SUMMARY` or `DESCRIPTION`

**Comment by u01jmg3** [comment]
Where did the ICS data come from? Looks like the encoding has gone awry which makes it extremely difficult to parse as things like newlines are not being represented correctly. This means I don't know where one line ends and another begins.

**Comment by nekromoff** [comment]
Google calendar, but old and it is possible that some characters are
historically mangled. However, I have been using your library for over a
year now without a glitch like this.

I have now tried to import a different time range and you are right, it
passed with success. I am going to investigate further and report.

**Comment by u01jmg3** [comment]
Yes please get back to me if you find out specifically what data is tripping things up.

Nothing has changed recently in `Events.php` - last edit made 6 months ago.

In the meantime I will see if I can harden the code to prevent memory issues.

**Comment by u01jmg3** [comment]
One thing you could try is applying [this function](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L2056-L2065) to [this line](https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/Event.php#L198) in `Event.php`

**Comment by u01jmg3** [comment]
@nekromoff: how are you getting on?

**Comment by nekromoff** [comment]
It was an external event, created by Microsoft calendar, but unfortunately the user deleted it so I can not debug it anymore. After the deletion, this issue has not appeared again.

**Comment by cyberkeiler** [comment]
Hi there. Have the same problem parsing customers ics Export of a google calendar. I'm pretty sure they used emojis or other special characters in their titles & descriptions. Is there any tipp to avoid this error yet? Any manual reformatting?

**Comment by u01jmg3** [comment]
@cyberkeiler: as I said before in order to look at fixing this I would need the ICS causing the issue. I would suggest opening a new issue when you have isolated the relevant ICS.
