### ISSUE TITLE
Undiscoverable dtstart_tz and dtend_tz properties of Event class

### ISSUE THREAD

**Issue by coatesap** [u01jmg3/ics-parser#275]
At the moment, the `dtstart_tz` and `dtend_tz` properties of the `ICal\Event` class are not discoverable by static analysis tools as they are declared dynamically, and hence any access to them will appear as an error in an IDE.

Is there any reason why they can't be declared as permanent properties on the Event class, even if they are nullable?

I'm happy to open a PR for this if that seems reasonable?

**Comment by u01jmg3** [comment]
It was added many years prior probably in an attempt to keep things clean and allow a simple `isset()` to be used.

Happy to accept a PR though and we can default to `null`
