### ISSUE TITLE
Yearly not working

### ISSUE THREAD

**Issue by craCH** [u01jmg3/ics-parser#282]
The following example shows the event every month at the 14th:

BEGIN:VEVENT
DTSTART;VALUE=DATE:20200214
DTEND;VALUE=DATE:20200215
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTHDAY=14
DTSTAMP:20210307T210302Z
UID:cgo3ee1lcgsjgb9n6kp30b9k71ijib9ockqj2b9pc5i3gdb168qjechk6k@google.com
CREATED:20200216T100459Z
DESCRIPTION:
LAST-MODIFIED:20200216T100459Z
LOCATION:
SEQUENCE:1
STATUS:TENTATIVE
SUMMARY:Geburtstag Monika
TRANSP:TRANSPARENT
END:VEVENT

**Comment by s0600204** [comment]
> The [...] example shows the event every month at the 14th

Yes, yes it does: this would be the expected output for that `RRULE`.

If you only wish it to repeat on February 14, either remove the `BYMONTHDAY` stanza or add `BYMONTH=2`.

If you are expecting a different output with that `RRULE`, please state what you expect.

**Comment by craCH** [comment]
This is the standard ics output from Google Calendar. So I can't change it.

**Comment by u01jmg3** [comment]
Google Calendar does provide recurrence options for repeating events: https://support.google.com/calendar/answer/37115

**Comment by u01jmg3** [comment]
Closing due to a lack of activity
