### ISSUE TITLE
dtend array not initiated for an event

### ISSUE THREAD

**Issue by nekromoff** [u01jmg3/ics-parser#283]
> :information_source:
> - Firstly, check you are using the latest version (`dev-master`) as the problem may already have been fixed.
> - It is **essential** to be provided with the offending iCal causing the parser to behave incorrectly.
>   - Best to upload the iCal file directly to this issue
> - [Create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
>   - Minimal - use as little code as possible that still produces the same problem
>   - Complete - provide all parts needed to reproduce the problem
>   - Verifiable - test the code you're about to provide to make sure it reproduces the problem

- PHP Version: `7.4.16`
- PHP date.timezone: `Slovakia/Bratislava`
- ICS Parser Version: `2.2.2`
- Linux

### Description of the Issue:
`$event->dtend_array` does not exist
It should exist for every event, right? Even if empty...

### Steps to Reproduce:
Event dump:
![image](https://user-images.githubusercontent.com/8550349/112444929-dd052700-8d4e-11eb-9a33-29abe290d8b3.png)

**Comment by u01jmg3** [comment]
As per the issue template:

> _It is **essential** to be provided with the offending iCal causing the parser to behave incorrectly._

**Comment by nekromoff** [comment]
Since it is a private calendar, this is often not an option. I can however
provide complete object in question (with PII data removed).

**Comment by nekromoff** [comment]
hopefully the whole offending thing from `ics` file (xxxxx = redacted):
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20210303
DTSTAMP:20210325T095118Z
UID:xxxxxxxx
CREATED:20210310T142409Z
DESCRIPTION:
LAST-MODIFIED:20210310T142409Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:xxxxxxxxxx
TRANSP:TRANSPARENT
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H10M0S
END:VALARM
END:VEVENT
```

**Comment by u01jmg3** [comment]
Thanks - so this is an event without an end date therefore the `dtend_array` key is not created/populated. This is expected.

**Comment by nekromoff** [comment]
Ok, thanks for the clarification.
