### ISSUE TITLE
Allow set HTTP Protocol Version

### ISSUE THREAD

**Issue by clintallan** [u01jmg3/ics-parser#295]
I am using your package to parse ics files.
I currently have an issue with booking.com feeds.
This is caused by using HTTP protocol 1.1.
If we set it to 1.0 it fixes the issue.
I have a branch locally to fix the issue. This allows you to pass the HTTP protocol version into the initUrl method. Defaults to 1.1 if not passed in.
Happy to push it up and create a PR to resolve it rather than fork the project.

Thanks

**Comment by u01jmg3** [comment]
Please PR

**Comment by clintallan** [comment]
> Please PR

Need access to push

**Comment by u01jmg3** [comment]
Closed by #296
