### ISSUE TITLE
Deprecation notice using PHP 8.1

### ISSUE THREAD

**Issue by mklemme1** [u01jmg3/ics-parser#299]
I use PHP 8.1.3 and johngrogg/ics-parser (v3.1.0) via composer.

I get a deprecation notice
>  Deprecated: auto_detect_line_endings is deprecated in /local/home/klemme/ADFC/Wordpress/WordpressPlugins/adfc-kalender/vendor/johngrogg/ics-parser/src/ICal/ICal.php on line 500

I understand this will be removed in PHP 9. But perhaps you can have a look at it now anyway.

Thanks

**Comment by s0600204** [comment]
Thank you for bringing this to our attention (for some reason this isn't showing up in my log files despite also running `php 8.1.3`.)

----

Further reading:
* https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.standard
* https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated
