### ISSUE TITLE
Version specification advice in README needs updating.

### ISSUE THREAD

**Issue by mklemme1** [u01jmg3/ics-parser#300]
On https://packagist.org/packages/johngrogg/ics-parser I read:
>To access the latest stable branch (v2) use the following
>    To access new features you can require [dev-master](https://getcomposer.org/doc/articles/aliases.md#branch-alias)
>    {
>        "require": {
>            "johngrogg/ics-parser": "^2"
>        }
>    }

SInce version 3.1 is out, shouldn't it be `"johngrogg/ics-parser": "^3"`?

**Comment by mklemme1** [comment]
![2022-03-04_22-34](https://user-images.githubusercontent.com/3100268/156844785-85ac1d9e-8181-4be1-ba18-6a7eedad2439.png)

**Comment by s0600204** [comment]
Indeed it should be.

Feel free to submit a PR - the block comment at the top of `src/ICal/ICal.php` also needs updating.

**Comment by mklemme1** [comment]
I am not an expert on this.
I hope the PR is okay
