### ISSUE TITLE
Bump minimum version to PHP 7.4

### ISSUE THREAD

**Issue by tacman** [u01jmg3/ics-parser#308]
### Description of the Issue:

We can't update to the latest version of phpunit and support PHP 5.

### Steps to Reproduce:

* Install the latest version of PHP
* run composer install && composer test

```bash
tac@pop-os:~/survos/bundles/ics-parser$ composer test
> phpunit --colors=always
PHP Warning:  Private methods cannot be final as they are never overridden by other classes in /home/tac/survos/bundles/ics-parser/vendor/phpunit/phpunit/src/Util/Configuration.php on line 162
PHP Fatal error:  Cannot acquire reference to $GLOBALS in /home/tac/survos/bundles/ics-parser/vendor/phpunit/phpunit/src/Util/Configuration.php on line 504
Script phpunit --colors=always handling the test event returned with error code 255
```

**Comment by tacman** [comment]
On a related note, I used rector to update the code to PHP 7.4, and it went smoothly.  Although it's not necessary, PHP 7.4 allows for typed properties, which makes static analysis using tool like phpstan easier. Indeed, running phpstan on level 2 showed some issues.  For example

```php
    /**
     * Parses a duration and applies it to a date
     *
     * @param  string $date
     * @param  string $duration
     * @param  string $format
     * @return integer|\DateTime
     */
    protected function parseDuration($date, $duration, $format = self::UNIX_FORMAT)
    {
        $dateTime = date_create($date);
        $dateTime->modify(sprintf('%s year', $duration->y));
```

$duration is marked as a string, but it's obviously an object, and typing it in PHP would ultimately be a better practice.  Not sure if it's worth the effort to make these changes, though.

**Comment by u01jmg3** [comment]
See PR #309, 2c8cf55
