### ISSUE TITLE
Minor phpdoc change for ICal::parseDuration()

### ISSUE THREAD

**Issue by kktsvetkov** [u01jmg3/ics-parser#310]
Hi, the phpdoc for `ICal::parseDuration()` might be off as it states `$duration` is string, while looking at the code it seems to be a `DateInterval` object as its properties are being used such as `$duration->y`:
```php 
    /**
     * Parses a duration and applies it to a date
     *
     * @param  string $date
     * @param  string $duration
     * @param  string $format
     * @return integer|\DateTime
     */
    protected function parseDuration($date, $duration, $format = self::UNIX_FORMAT)
    {
        $dateTime = date_create($date);
        $dateTime->modify("{$duration->y} year");
        $dateTime->modify("{$duration->m} month");
        $dateTime->modify("{$duration->d} day");
        $dateTime->modify("{$duration->h} hour");
        $dateTime->modify("{$duration->i} minute");
        $dateTime->modify("{$duration->s} second");
        ...
```

**Comment by kktsvetkov** [comment]
Also, it seems the last argument for `ICal::parseDuration()` is never used. It is `$format` but the only where place `ICal::parseDuration()` is called, it is `null`. Perhaps that last argument can be dropped, as the returned output is a `DateTime` and once you receive that object you can format it as you like.

**Comment by u01jmg3** [comment]
See 2c8cf55
