### ISSUE TITLE
ICal\Event gives deprecation warnings for php8.2

### ISSUE THREAD

**Issue by Hikariii** [u01jmg3/ics-parser#315]
- PHP Version: `8.2`
- PHP date.timezone: `*`
- ICS Parser Version: `3.2.0`
- Windows && Mac && Linux

### Description of the Issue:
Php 8.2 

### Steps to Reproduce:

1. Use a php8.2 environment
2. run `$event = new \Ical\Event(['foo' => ['bar', 3])`

The following deprecation warings occur:
```
NOTICE: PHP message: PHP Deprecated: Creation of dynamic property ICal\Event::$foo is deprecated in src/ICal/Event.php on line 140
```
```
NOTICE: PHP message: PHP Deprecated: Use of "self" in callables is deprecated in src/ICal/Event.php on line 155
```

Running the testsuite in php8.2 causes the same notices.

**Comment by Hikariii** [comment]
@u01jmg3 Don't really know what the release-strategy is but i'd love for this to be a patch release on 3.2 and installable via composer.

**Comment by u01jmg3** [comment]
Done

**Comment by room34** [comment]
This shunting of dynamic properties into the `additionalProperties` array is forcing me to rewrite parts of my application.

[https://php.watch/versions/8.2/dynamic-properties-deprecated#AllowDynamicProperties](https://php.watch/versions/8.2/dynamic-properties-deprecated#AllowDynamicProperties)

It seems from the above that this issue could have been resolved in a way that caused less disruption to existing applications.

**Comment by u01jmg3** [comment]
Can you raise a new issue explaining the problem and the rewrite that's required? I'm also happy to review another PR
