### ISSUE TITLE
Undefined array key warning if DESCRIPTION contains HTML ampersand entities

### ISSUE THREAD

**Issue by room34** [u01jmg3/ics-parser#317]
- PHP Version: `8.1.2`
- PHP date.timezone: `America/Chicago`
- ICS Parser Version: `3.2.1`
- Linux

### Description of the Issue:

If the .ics file contains an ampersand entity in the DESCRIPTION (though I suspect the issue may just be the semicolon), I get the following PHP warnings:

*Warning: Undefined array key 4 in /var/www/.../ics-parser/src/ICal/ICal.php on line 1033*

*Warning: Undefined array key 4 in /var/www/.../ics-parser/src/ICal/ICal.php on line 1042*

(The attached file has a `.txt` extension appended so GitHub will accept the upload.)
[AmpersandEntityExample.ics.txt](https://github.com/u01jmg3/ics-parser/files/10900098/AmpersandEntityExample.ics.txt)

### Steps to Reproduce:

Use attached example which contains an HTML ampersand entity in the DESCRIPTION. This is an actual example from one of my users, with all events other than the one containing the ampersand entity removed.

**Comment by u01jmg3** [comment]
Thanks for logging this issue. A PR is welcome.

**Comment by u01jmg3** [comment]
`??` can be rewritten as just a standard ternary (`is_null($var) ? $var : ''`)

**Comment by u01jmg3** [comment]
I've focussed on the non-breaking space for now as it affects [the unfolding mechanism](https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html) that's permitted in the iCal spec.
