### ISSUE TITLE
File from URL not working

### ISSUE THREAD

**Issue by teo2600** [u01jmg3/ics-parser#321]
I am not able to have it working using my private ics calendar URL (https://calendar.google.com/calendar/ical/XXX/XXX/basic.ics) instead of the downloaded file (basic.ics).

When I use the downloaded file it is retrieving the events, but when I use the link to the same file it retrieves nothing...

**Comment by u01jmg3** [comment]
As the issue template has not been filled in, you've given me very little to go on. Once the info has been provided I can look at your issue.

**Comment by s0600204** [comment]
See #322 for continuation.
