### ISSUE TITLE
Not able to show the correct Timezone time

### ISSUE THREAD

**Issue by teo2600** [u01jmg3/ics-parser#323]
### PHP Version

8.2

### PHP date.timezone

Europe/Rome

### ICS Parser Version

3.2.1

### Operating System

Linux

### Description

Considering the "examples", I would like:

1) To display the time in the correct Timezone (Europe/Rome), but even setting that it keeps displaying the UTC time: how could I solve this? 

2) To display not only the summary and start time of the event, but also the end time and the description: how?

Thank you very much!

### Steps to Reproduce

BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:PhD38it
X-WR-TIMEZONE:Europe/Rome
BEGIN:VEVENT
DTSTART:20230509T070000Z
DTEND:20230509T080000Z
DTSTAMP:20230503T194722Z
UID:[XXX@google.com](mailto:XXX@google.com)
CREATED:20230503T144541Z
DESCRIPTION:
LAST-MODIFIED:20230503T150822Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Prova
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

**Comment by u01jmg3** [comment]
@teo2600: has the above solved your issue?

**Comment by teo2600** [comment]
I solved this issue using a workaround: calling DTSTART_TZ and DTEND_TZ instead...
Thanks.

**Comment by ingridbeilova** [comment]
> I solved this issue using a workaround: reading DTSTART_TZ and DTEND_TZ instead... Thanks.

Did that work for you? For me, `dtstart` and `dstart_tz` return the same values, so I have to read from `dtstart_array` to get the correct timezone.
