### ISSUE TITLE
Deprecated function 'auto_detect_line_endings' in ini_set for php 8

### ISSUE THREAD

**Issue by hcrofts7527** [u01jmg3/ics-parser#325]
After upgrading to php 8 this error appeared.

Deprecated function: auto_detect_line_endings is deprecated in ICal\\ICal->\__construct() (line 500 of /var/www0/vendor/johngrogg/ics-parser/src/ICal/ICal.php)

For now it looks like just the 'auto_detect_line_endings' is deprecated, but it looks like the INI directive will be removed completely in php 9 according to https://php.watch/versions/8.1/auto_detect_line_endings-ini-deprecated

**Comment by u01jmg3** [comment]
We already have this from #299:

https://github.com/u01jmg3/ics-parser/blob/15d7f0d8d90be99b791fac48c12f1abd74441206/src/ICal/ICal.php#L508-L510
