### ISSUE TITLE
Emoji's no longer display correctly in v3.3.0

### ISSUE THREAD

**Issue by feisar-uk** [u01jmg3/ics-parser#327]
### PHP Version

8.2.10

### PHP date.timezone

Europe/London

### ICS Parser Version

3.3.0

### Operating System

Linux

### Description

In v3.3.0 Emoji's in the Event SUMMARY field now display as � characters (question mark in a diamond) rather than the correct Emoji characters. Downgrading back to v3.2.1 restores the correct Emoji display.

### Steps to Reproduce

Run the code below with the attached `test.ics` file both on v3.2.1 (and earlier) and v3.3.0 to observe the difference.

With ics-parser v3.2.1

![correct-emoji](https://github.com/u01jmg3/ics-parser/assets/8984413/d7f875f0-c35a-44cd-905b-fb28a1bdd4b9)

With ics-parser v3.3.0

![incorrect-emoji](https://github.com/u01jmg3/ics-parser/assets/8984413/912c0acb-abdc-44bb-b9b9-72c5fb1d61b9)

```
<?php
require_once '../vendor/autoload.php';

use ICal\ICal;

try {
    $ical = new ICal('test.ics');
} catch (\Exception $e) {
    die($e);
}

var_dump($ical->events());
```

[test.ics.zip](https://github.com/u01jmg3/ics-parser/files/12850875/test.ics.zip)

**Comment by u01jmg3** [comment]
Confirmed that this was caused by 9df6990

**Comment by u01jmg3** [comment]
Try [`v3.3.1`](https://github.com/u01jmg3/ics-parser/releases/tag/v3.3.1)

**Comment by feisar-uk** [comment]
Working fine again now. Thank you for the speedy fix. 👍🏻
