### ISSUE TITLE
Help request: how to filter events by now() +/- X minutes

### ISSUE THREAD

**Issue by tacman** [u01jmg3/ics-parser#331]
### PHP Version

8.3

### PHP date.timezone

all

### ICS Parser Version

3.2.1

### Operating System

Linux

### Description

This is such a cool library.

I'm trying to figure out how to find out what events are going on right now, +/- some number of minutes.  Is there a way to do that?  

Thanks.  

### Steps to Reproduce

This isn't a bug report, rather a request for help / documentation.  thanks.

**Comment by u01jmg3** [comment]
Minutes - no
Days - yes

[Checkout `$filterDaysBefore` and `$filterDaysAfter`](https://github.com/u01jmg3/ics-parser/blob/master/README.md#variables)

**Comment by tacman** [comment]
oops, forgot to close.  Thanks!
