### ISSUE TITLE
Compatibility with webcal url

### ISSUE THREAD

**Issue by dcr31000** [u01jmg3/ics-parser#332]
### PHP Version

8.1.20

### PHP date.timezone

Europe/Paris

### ICS Parser Version

3.3.1

### Operating System

Debian

### Description

Hello,

I'm trying to parse an ics with webcal url format (webcal://{}-caldav.icloud.com/published/{}).
The url is valided by https://icalendar.org/validator.html

When i'm using ics-parser, I got this error:
`ErrorException: Warning: file_exists(): Unable to find the wrapper "webcal" - did you forget to enable it when you configured PHP? in {}/vendor/johngrogg/ics-parser/src/ICal/ICal.php:2571`

Is ics-parser compatible with webcal ?

### Steps to Reproduce

Get a webcal url (with iCloud for example)
Do new ICal({url})

**Comment by u01jmg3** [comment]
It isn't - PR welcome

**Comment by u01jmg3** [comment]
Please feel free to reopen if/when you'd like to submit a PR.
