### ISSUE TITLE
Non-breaking spaces are removed from DESCRIPTION

### ISSUE THREAD

**Issue by albig** [u01jmg3/ics-parser#333]
### PHP Version

8.2.15

### PHP date.timezone

Europe/Berlin

### ICS Parser Version

3.3.1 / master

### Operating System

Linux

### Description

If an event contains a non-breakable space (`\xA0`) in the `DESCRIPTION`, this space will be removed by ics-parser. This happens in `removePrintableCharacters` in https://github.com/u01jmg3/ics-parser/blob/master/src/ICal/ICal.php#L2463. 

I wonder, why this is done and why this space is not replaced by an ordinary space instead?

A Sample ICS-File is this:
[E6F2B1A6-D81E-4BAB-9680-97CCB60AFB78.ics.txt](https://github.com/u01jmg3/ics-parser/files/14342234/E6F2B1A6-D81E-4BAB-9680-97CCB60AFB78.ics.txt)

The resulting description is

![2024-02-20_10-37](https://github.com/u01jmg3/ics-parser/assets/3354500/117e824e-c89a-4080-a01e-33f4778a8e3e)

Of course, this can be fixed easily by the client itself and in the sample case, there is no need to use non-breakable spaces. But you know, not everybody is a nerd ;-)

Importing the same event into Thunderbird or the Linux cinnamon calendar just keeps the non-breaking space as is.

### Steps to Reproduce

* Use Libreoffcie writer and write some text with non-breakable spaces (CTRL+SPACE)
* copy the text into a nextcloud calendar event
* import the nextcloud calendar via ICS with ics-parser

**Comment by u01jmg3** [comment]
PR welcome
