### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by stfnhmplr** [u01jmg3/ics-parser#339]
### PHP Version

8.2.20

### PHP date.timezone

Europe/Berlin

### ICS Parser Version

3.4.0

### Operating System

Linux

### Description

With updating from version 3.3.1 to 3.4 the authentication does no longer work.
Error message: `file(https://example.com/ics): Failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized`

### Steps to Reproduce

```php
$ical = new ICal('ical.ics');

// real url exchanged with example url
$ical->initUrl('https://example.com/ics', 'username', 'password');
```

This is basically the code of the example you provided. This works in 3.3.1 without any issues. After updating to 3.4, the server responds with the error mentioned above. After downgrading to 3.3.1 it works again.

**Comment by u01jmg3** [comment]
Can you try `dev-master` and check that fixes your issue, please?

**Comment by u01jmg3** [comment]
Pushed 23b6ada

Can you try `dev-master` and check that fixes your issue, please?

**Comment by stfnhmplr** [comment]
Wow, that was fast. It works perfectly with dev-master. Thank you very much!

**Comment by u01jmg3** [comment]
Shall cut a new release soon so look out for v3.4.1
