### ISSUE TITLE
Recurring all day events with time information

### ISSUE THREAD

**Issue by rashnk** [u01jmg3/ics-parser#50]
Parser adds **T000000** in allday events, it should be date only

```
SUMMARY: test 1
DTSTART: 20160202T000000 - UNIX-Time: 1454351400
DTEND: 20160203T000000
DTSTAMP: 20110121T195741Z
UID: dh3fki5du0opa7cs5n5s87ca00@google.com
CREATED: 20110119T141901Z
LAST-MODIFIED: 20150409T150000Z
DESCRIPTION: 
LOCATION: 
SEQUENCE: 
STATUS: CONFIRMED
TRANSP: TRANSPARENT
ORGANIZER: 
ATTENDEE(S): 
```

**Comment by u01jmg3** [comment]
This is a bug because as [the spec](http://www.kanzaki.com/docs/ical/dtstart.html) states, `DSTART` can be a date-time **or a date**.

PR welcome

**Comment by rashnk** [comment]
u can check whether the date contains time information as this :  if strlen(datevalue)>8 // this means not all day event, select date format depends on this

**Comment by u01jmg3** [comment]
- Is this issue still present with the latest `dev-master`?
- Can you provide the exact iCal snippet which caused your issue?

**Comment by u01jmg3** [comment]
Over a month and no feedback so closing issue - happy to re-open if required.
