### ISSUE TITLE
Add simple ranges; e.g., get next 30 days of events

### ISSUE THREAD

**Issue by philip** [u01jmg3/ics-parser#57]
It'd be nice to get the upcoming (and/or past) X days of calendar events. There is eventsFromRange() today but it's different. This is a feature request.

**Comment by u01jmg3** [comment]
Feel free to PR; this library is not currently in active development. Bugs will be fixed but enhancements will be added to a prioritised queue.

**Comment by u01jmg3** [comment]
Closed by PR [#96](https://github.com/u01jmg3/ics-parser/pull/96)
