### ISSUE TITLE
ICS from Office 365 not skipping EXDATE

### ISSUE THREAD

**Issue by tdrusk** [u01jmg3/ics-parser#65]
A bunch of my recurring events were showing up that were individually deleted out of a series. I was able to hack around it. Any idea what is wrong with the event below that would be causing it not to skip?

```
BEGIN:VEVENT
DESCRIPTION:\n\n
RRULE:FREQ=MONTHLY;UNTIL=20160908T223000Z;INTERVAL=1;BYDAY=2TH
EXDATE;TZID=Eastern Standard Time:20160609T183000,20160714T183000,20160811T
 183000
UID:040000008200E00074C5B7101A82E00800000000A0CCE414EE70CF01000000000000000
 010000000BE1B73167CFE704F9795393E7E745F5D
SUMMARY:Personnel
DTSTART;TZID=Eastern Standard Time:20160414T183000
DTEND;TZID=Eastern Standard Time:20160414T193000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160706T150005Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:202
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

**Comment by u01jmg3** [comment]
A quick google and the status of your event isn't correct if you want it to be deleted: https://stackoverflow.com/questions/356598/delete-calendar-event-using-icalendar-file-import-outlook-2003-problem#357641

**Comment by tdrusk** [comment]
Sorry if I am misunderstanding. This is a recurring event. 

Let's take this one for example:

```
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20160706T161104Z
DTEND;TZID="Eastern Standard Time":20160409T110000
DTSTAMP:20160706T150005Z
DTSTART;TZID="Eastern Standard Time":20160409T090000
EXDATE;TZID="Eastern Standard Time":20160528T090000,20160625T090000,2016070
	9T090000
LAST-MODIFIED:20160707T182011Z
LOCATION:Sanctuary
PRIORITY:5
RRULE:FREQ=WEEKLY;COUNT=26;BYDAY=SA
SEQUENCE:0
SUMMARY:Martha practices
TRANSP:OPAQUE
UID:040000008200E00074C5B7101A82E0080000000020F6512D0B48CF01000000000000000
	01000000058BFB8CBB85D504CB99FBA637BCFD6BF
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

I opened the calendar in Outlook 2016 and deleted the occurrence on 7/9/2016. This is reflected in the EXDATE. This is the only entry in the ICS file of 'Martha Practices'. It seems the status would be 'Confirmed', unless there is an EXDATE - in which there is no event. 

I made an if statement in my code which checks to see if the event start date matches an EXDATE. If so, don't show it.
