### ISSUE TITLE
Not showing event over multiple days

### ISSUE THREAD

**Issue by stianjaco** [u01jmg3/ics-parser#73]
If I have an event that starts Monday and ends Sunday, the event will not show if using `eventsFromRange()` even if the day is right.

**Comment by u01jmg3** [comment]
Feel free to PR; this library is not currently in active development. Bugs will be fixed but enhancements will be added to a prioritised queue.

**Comment by u01jmg3** [comment]
If you provide an iCal snippet that will allows us to replicate the problem on our end.

**Comment by u01jmg3** [comment]
- No iCal snippet provided so unable to reproduce the problem
- Happy to re-open if one is provided
