### ISSUE TITLE
Check if timezones are valid

### ISSUE THREAD

**Issue by jeromecombes** [u01jmg3/ics-parser#75]
Timezones detected into ICS files have to be checked to avoid PHP errors.
Some ICS files return something like `TZID:GMT+02.000/+03.000` which is not a PHP timezone format and this might generate errors.

I offer an enhancement that allow the user to define a default timezone which will be used if a wrong timezone is detected with the php function `timezone_identifiers_list`.

**Comment by u01jmg3** [comment]
PR submitted: ~~#76~~
