### ISSUE TITLE
Quoted organizer gets stripped

### ISSUE THREAD

**Issue by blodan** [u01jmg3/ics-parser#86]
Hi!

If the organizer line in the ics file is as follows:
`ORGANIZER;CN="My Name":mailto:my.name@mydomain.com`

`keyValueFromString()` returns `&quot` because of the use of `htmlspecialchars()`, I'm not entirely sure why `htmlspecialchars()` is needed there, removing it solves the semicolon issue that the code is using as delimiter as `"` is `&quote;` otherwise

**Comment by blodan** [comment]
I'm using a ics file from Zimbra btw where as Zimbra seems to quote all names that contains multibyte chars such as å ä ö

**Comment by u01jmg3** [comment]
As per the [contributing guidelines](https://github.com/u01jmg3/ics-parser/blob/master/CONTRIBUTING.md)...

> _It is also extremely useful to be provided with an iCal snippet causing the parser to behave incorrectly_

**Comment by u01jmg3** [comment]
> If the organizer line in the ics file is as follows:
> `ORGANIZER;CN="My Name":mailto:my.name@mydomain.com`
> `keyValueFromString()` returns `&quot` because of the use of `htmlspecialchars()`

This should be fixed by https://github.com/u01jmg3/ics-parser/commit/7fdaebe53bfa3bff8bc3c6b7b567c3fbd3242f30

**Comment by u01jmg3** [comment]
Over a month and no feedback so closing issue - happy to re-open if required.
