### ISSUE TITLE
Fails on bad timezone

### ISSUE THREAD

**Issue by ohryan** [u01jmg3/ics-parser#87]
I am working with a server that returns:

```
BEGIN:VTIMEZONE
TZID:Central Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
```

`TZID:Central Standard Time` is not a valid timezone identifier so the code fails on [`ICal.php:459`](https://github.com/u01jmg3/ics-parser/blob/4032ae36dc6a6cb0c858ec40363c6bbeb68ac565/src/ICal/ICal.php#L459).

**Comment by u01jmg3** [comment]
Thanks - will take a look

**Comment by u01jmg3** [comment]
Closing - same reason for closing PR #88
