### ISSUE TITLE
Timezone issue on recurring events

### ISSUE THREAD

**Issue by svbender** [u01jmg3/ics-parser#90]
Hi,

currently I have a problem with yearly events with wrong timezones. I am using a Google ics file.

If I add a "fullday" event (e.g. Birthday) the entry does not have a time, only a date for DTSTART (20131127) and DTEND (20131128). The parser adds a time to the date (20161127T230000Z), which is 230000 (UTC 11pm) generated from the timestamp.

I guess for such events there should not be a generated time?

**Comment by u01jmg3** [comment]
As per the contributing guidelines...

> _It is also extremely useful to be provided with an iCal snippet causing the parser to behave incorrectly_

**Comment by svbender** [comment]
My PHP setup was on "Europe/Berlin" Timezone and not UTC. Therefore I had issues with the timezone of the events. Sorry for bugging you.

I wanted to check dtstart/dtend, if there is only a date (without time) it is a "fullday" event.
But i can also check for "000000 " as the time part of the string, if i set the timezone correctly :-)
So not a bug, but confusing for the "fullday" events when a time string is added.

You can check it by yourself if you want. This file contains only a date:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Birthdays
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;VALUE=DATE:20131128
DTEND;VALUE=DATE:20131129
RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=11;BYMONTHDAY=28
DTSTAMP:20161109T191726Z
UID:abcd@google.com
CREATED:20131025T224557Z
DESCRIPTION:
LAST-MODIFIED:20161107T203541Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:Birthday of someone
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

Anyway, good job. Thank you for the great parser!
