### ISSUE TITLE
Notice: Undefined variable: dayRecurringTimestamp in /ICal.php on line 902

### ISSUE THREAD

**Issue by Wikibear** [u01jmg3/ics-parser#92]
Get this notice, cause `dayRecurringTimestamp` is not initiated.

**Comment by u01jmg3** [comment]
As per the [contributing guidelines](https://github.com/u01jmg3/ics-parser/blob/master/CONTRIBUTING.md)...

> _It is also extremely useful to be provided with an iCal snippet causing the parser to behave incorrectly_

**Comment by Wikibear** [comment]
Sorry, for me it was clear that there is a not initiated string in month case. I will send you my using code shortly and ical file link also. 

Thanks.

**Comment by Wikibear** [comment]
`<?php
	$path = "";
	$filedata = "";
	require $path.'class/ICal/ICal.php';
	require $path.'class/ICal/EventObject.php';
	use ICal\ICal;
	$ical = new ICal("https://www.google.com/calendar/ical/um8r7ne385gpag3mla4undh2u0%40group.calendar.google.com/public/basic.ics");

	function nl2br2($string) {
		$string = str_replace(array("\\n", "\\, "), "<br />", $string);
		$string = preg_replace('@(https?://([-\w\.]+[-\w])+(:\d+)?(/([\w/_\.#-]*(\?\S+)?[^\.\s])?)?)@', '<a href="$1" target="_blank">$1</a>', $string);
		return $string;
	} 

	function template($summary,$start,$end,$description,$location){
		$filedatareturn = "<p align=\"left\"><b>Was:".nl2br2($summary)."</b><br />";
		$filedatareturn .= "Wann: ".$start."<br />";
		$filedatareturn .= "Wo: ".nl2br2($location)."<br />";
		$filedatareturn .= "Beschreibung: ".nl2br2($description)."</p><hr />";
		return $filedatareturn;
	}
	$events = $ical->events();
	$events = $ical->eventsFromRange(date('Y-m-01'), date('Y-m-t'));
	$i=1;
	foreach($events as $event){
		echo $i;
		$filedata .= template($event->summary,date('d.m.Y H:i', $ical->iCalDateToUnixTimestamp($event->dtstart)),date('H:i', $ical->iCalDateToUnixTimestamp($event->dtend)),$event->description,$event->location);
		$i++;
	}
	echo $filedata;
?>`

Today there is an entry that doesn't exist. There is no event at 29.11.2016!

Was:LCBS Treffen
Wann: 29.11.2016 19:00

This event isn't true. And if you check iCal you wouldn't find this entry. You get four must be three events.

**Comment by u01jmg3** [comment]
- Thanks - just needed the iCal snippet (https://www.google.com/calendar/ical/um8r7ne385gpag3mla4undh2u0%40group.calendar.google.com/public/basic.ics)

**Comment by u01jmg3** [comment]
@Wikibear: grab `dev-master` again and your issue should be solved
