### ISSUE TITLE
Missing event

### ISSUE THREAD

**Issue by Wikibear** [u01jmg3/ics-parser#93]
https://www.google.com/calendar/ical/um8r7ne385gpag3mla4undh2u0%40group.calendar.google.com/public/basic.ics

Get a fourth event that doesn't exist if I query:

`$events = $ical->eventsFromRange(date('2016-11-01'), date('2016-11-30'));`

Happens from November 2016. Get four events but that must be three.

This is my code that I use:

```php
function nl2br2($string) {
    $string = str_replace(array("\\n", "\\, "), "<br />", $string);
    $string = preg_replace('@(https?://([-\w\.]+[-\w])+(:\d+)?(/([\w/_\.#-]*(\?\S+)?[^\.\s])?)?)@', '<a href="$1" target="_blank">$1</a>', $string);
    return $string;
}

function template($summary, $start, $end, $description, $location) {
    $filedatareturn = "<p align=\"left\"><b>Was:".nl2br2($summary)."</b><br />";
    $filedatareturn .= "Wann: ".$start."<br />";
    $filedatareturn .= "Wo: ".nl2br2($location)."<br />";
    $filedatareturn .= "Beschreibung: ".nl2br2($description)."</p><hr />";
    return $filedatareturn;
}

$events = $ical->events();
$events = $ical->eventsFromRange(date('2016-11-01'), date('2016-11-30'));
$i = 1;

foreach($events as $event) {
    echo $i;
    $filedata .= template($event->summary,date('d.m.Y H:i', $ical->iCalDateToUnixTimestamp($event->dtstart)), date('H:i', $ical->iCalDateToUnixTimestamp($event->dtend)), $event->description, $event->location);
    $i++;
}

echo $filedata;
```

**Comment by u01jmg3** [comment]
The recent changes to `eventsFromRange()` may fix your issue - can you try again with `dev-master`?

**Comment by Wikibear** [comment]
Doesn't work. I get two dates: LCBS Treffen 25.11.2016 and LCBS Treffen 29.11.2016. The last at 29.11.2016 is not present in iCal file. This isn't true.

**Comment by u01jmg3** [comment]
Just ran the parser against your iCal feed and it returned 4 events for the range `2016-11-01` to `2016-11-30`.

--

1. LCBS Treffen (25-11-2016 18:00)
   - `DTSTART;TZID=Europe/Berlin:20161125T190000`
   - `DTEND;TZID=Europe/Berlin:20161125T210000`
1. LCBS Treffen (25-11-2016 18:00)
   - `DTSTART;TZID=Europe/Berlin:20161125T190000`
   - `DTEND;TZID=Europe/Berlin:20161125T210000`
   - `RRULE:FREQ=MONTHLY;UNTIL=20170323T225959Z;BYDAY=4FR`
1. DGLR-Vortrag: Air Breathing Propulsion - Quo vadis? (28-11-2016 18:00)
   - `DTSTART:20161128T180000Z`
   - `DTEND:20161128T190000Z`
1. Auswahl Bild des Monats (29-11-2016 23:00)
   - `DTSTART;VALUE=DATE:20121129`
   - `DTEND;VALUE=DATE:20121201`
   - `RRULE:FREQ=MONTHLY;BYMONTHDAY=29`
   
--

- What is the summary of the event you are expecting to see?

**Comment by u01jmg3** [comment]
Over a month and no feedback so closing issue - happy to re-open if required.

**Comment by Wikibear** [comment]
Sorry for no feedback!

Number 1 and 2 are wrong. But i don't understand it. There is only Number 1 or Number 2 but not both. So is that a google error? The second seems to be ok. Its really each 4fr.
