### ISSUE TITLE
X-WR-TIMEZONE causes EXDATE of series to be ignored

### ISSUE THREAD

**Issue by dominikschreiber** [u01jmg3/ics-parser#98]
## Issue Description

I'm experiencing deleted series entries of a google calendar being shown in the `$ical->eventsFromRange` result. In my attempt to find out why this happens, I observed that `X-WR-TIMEZONE:Europe/Berlin` seems to cause the `EXDATE` to be ignored. If you remove this line, the `EXDATE` has effect.

See a minimal example below.

Sadly I'm too bad of a php developer to fix this with a pull request, but I hope you can work with the information I have here.

## Minimal Example

```ics
# file: basic.ics
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
DTSTART:20161205T140000
DTEND:20161205T160000
RRULE:FREQ=MONTHLY;BYDAY=1MO
EXDATE:20170102T140000
DTSTAMP:20161206T211738Z
SEQUENCE:0
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

```php
<?php // file: index.php
date_default_timezone_set('europe/berlin');
$ical = new ICal(explode("\r\n", file_get_contents("basic.ics")));
?>
<ul><?php foreach ($ical->eventsFromRange("2017-01-01", "2017-03-31") as $e) { ?>
  <li><?php echo strftime("%d.%m.%y", $ical->iCalDateToUnixTimestamp($e->dtstart)); } ?>
</ul>
```

## Expected Result

- 06.02.17
- 06.03.17

## Actual Result

- **02.01.17**
- 06.02.17
- 06.03.17

**Comment by u01jmg3** [comment]
- Just ran the parser against your snippet and it produced what was expected.

<img width="593" alt="x" src="https://cloud.githubusercontent.com/assets/1266205/20982639/5359f066-bcb1-11e6-8f30-e4faa142f83c.png">

- As per the issue guidelines, have you checked you are using the latest version (`dev-master`)?

**Comment by dominikschreiber** [comment]
I just required `dev-master` again, and the following php code produces the very error I reported:

```php
<?php
require_once "./vendor/autoload.php";

use ICal\ICal;

date_default_timezone_set('europe/berlin');
$ical = new ICal([
	"BEGIN:VCALENDAR",
	"VERSION:2.0",
	"CALSCALE:GREGORIAN",
	"METHOD:PUBLISH",
	"X-WR-TIMEZONE:Europe/Berlin",
	"BEGIN:VEVENT",
	"DTSTART:20161205T140000",
	"DTEND:20161205T160000",
	"RRULE:FREQ=MONTHLY;BYDAY=1MO",
	"EXDATE:20170102T140000",
	"DTSTAMP:20161206T211738Z",
	"SEQUENCE:0",
	"STATUS:CONFIRMED",
	"TRANSP:OPAQUE",
	"END:VEVENT",
	"END:VCALENDAR"
]);
?>
<ul><?php foreach ($ical->eventsFromRange("2017-01-01", "2017-03-31") as $e) { ?>
  <li><?php echo strftime("%d.%m.%y", $ical->iCalDateToUnixTimestamp($e->dtstart)); } ?>
</ul>
```

the `composer.lock`:

```json
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "hash": "98fc99ce1fe7c330fb7fd50744f31354",
    "content-hash": "331ae74e9c8fb45274a735cf87c6b5c4",
    "packages": [
        {
            "name": "johngrogg/ics-parser",
            "version": "v2.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/u01jmg3/ics-parser.git",
                "reference": "2574be22e551abba0a47e4d695684c8e70911477"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/u01jmg3/ics-parser/zipball/2574be22e551abba0a47e4d695684c8e70911477",
                "reference": "2574be22e551abba0a47e4d695684c8e70911477",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.0"
            },
            "require-dev": {
                "squizlabs/php_codesniffer": "^2.5"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "ICal": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Martin Thoma",
                    "email": "info@martin-thoma.de",
                    "role": "Original Developer"
                },
                {
                    "name": "John Grogg",
                    "email": "john.grogg@gmail.com",
                    "role": "Developer/Prior Owner"
                },
                {
                    "name": "Jonathan Goode",
                    "role": "Developer/Owner"
                }
            ],
            "description": "ICS file parser",
            "homepage": "https://github.com/u01jmg3/ics-parser",
            "keywords": [
                "ical",
                "ics"
            ],
            "time": "2016-11-28 00:00:22"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}
```

**Comment by u01jmg3** [comment]
@dominikschreiber: the latest `dev-master` should correct your issue. Can you try once last time, please?

**Comment by dominikschreiber** [comment]
Hey, sorry for me appearing offensive last time. I didn't mean it, you're doing a great work on your free time, and I really want to thank you for that.

**Commit f9f5866 fixes this issue.** For some reason, I have a huge performance drop from commit dde72dc (~3s to load https://calendar.google.com/calendar/ical/efg.ludwigshafen%40gmail.com/public/basic.ics, parse it, and render all events in a month in a table) over f9f5866 (~15s) to 4de3963 (~45s). I'm ok with that (use it for a script running once every 2 months), but this feels quite alarming...

**Comment by u01jmg3** [comment]
@dominikschreiber - glad to hear I have fixed the issue you reported in this issue. I shall look into the performance drop you mentioned and see what could be the cause.

**Comment by u01jmg3** [comment]
@dominikschreiber - I have analysed all 20 commits since the release of `v2.0.1` and found there to be 2 bottlenecks.

1. One surrounded using `iCalDateToUnixTimestamp()` in f9f5866 which always used a regex to parse the time zone
   - This has been changed in 9d44e5c to check that a time zone exists before trying to parse it
1. The second issue related to 48d285b and populating the `DTSTART_array`
   - The code was inefficient and has been improved in 9d44e5c

---

- Finally it is worth noting that in b7b3ee6 the recurrence rule logic to handle `EXDATE` data when a count is imposed has been corrected so that `EXDATE`s don't count towards an imposed count.
   - This means you may have more event data resulting in increased processing times.
